#!/usr/bin/python

import os

top = '.'
out = 'build'

def configure(conf):
    pass

def build(bld):
    mediafiles = bld.path.ant_glob ('**', excl='wscript')
    bld.install_files (os.path.join(bld.env['DATADIR'], 'media'), mediafiles, relative_trick=True)

def options(opt):
    pass
