#!/usr/bin/env python
from waflib.extras import autowaf as autowaf

I18N_PACKAGE = 'liblua'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    pass

def build(bld):
    obj=bld.stlib (source   = ['lua.cc', 'luastate.cc'],
                   cflags   = [ bld.env['compiler_flags_dict']['pic'] ],
                   cxxflags = [ bld.env['compiler_flags_dict']['pic'] ],
                   includes = ['.'],
                   export_includes = ['.'],
                   target = 'liblua',
                   uselib = [ 'SIGCPP', 'DL' ]
               )
    autowaf.ensure_visible_symbols (obj, True)

def shutdown():
    autowaf.shutdown()
