# -*- python -*-

import os
import os.path
import sys
import glob

fst_src = glob.glob('*.c')

Import('env install_prefix libraries')
fst = env.Clone(CC="winegcc")
fst.Append (CPPPATH=".")
fst.Merge ([libraries['glib2']])

if fst['VST']:
    a = fst.Object ('fst', 'fst.c')
    b = fst.Object ('fstinfofile', 'fstinfofile.c')
    c = fst.Object ('vstwin', 'vstwin.c')
    d = fst.Object ('vsti', 'vsti.c')
    e = fst.Object ('thread', 'thread.c')

    Default([a,b,c,d,e])
    
env.Alias('tarball', env.Distribute (env['DISTTREE'],
                                     fst_src + ['SConscript',
                                                'fst.h',
                                                'jackvst.h'
                                                ] ))

