#!/bin/sh
TOP=`dirname "$0"`/..
. $TOP/build/gtk2_ardour/ardev_common_waf.sh
LD_LIBRARY_PATH=$LD_LIBRARY_PATH
export ARDOUR_INSIDE_GDB=1
if test -n "`which gdb`"; then
	exec gdb --args $TOP/build/headless/hardour-$ARDOURVERSION "$@"
fi
if test -n "`which lldb`"; then
	exec lldb -- $TOP/build/headless/hardour-$ARDOURVERSION "$@"
fi
echo "neither gdb nor lldb was found."
