#!/bin/sh
. `dirname "$0"`/../build/headless/hardev_common_waf.sh
LD_LIBRARY_PATH=$LD_LIBRARY_PATH

TOP=`dirname "$0"`/..
if uname | grep -q arwin; then
	OBJSUPP="--suppressions=${TOP}/tools/objc.supp"
fi
export ARDOUR_RUNNING_UNDER_VALGRIND=TRUE
exec valgrind --tool=memcheck \
	$VALGRIND_OPTIONS \
	--track-origins=yes \
	--suppressions=${TOP}/tools/valgrind.supp \
	$OBJSUPP \
	$TOP/$EXECUTABLE --novst "$@"
