#!/bin/sh
VALGRIND_OPTIONS="$VALGRIND_OPTIONS --num-callers=50"
VALGRIND_OPTIONS="$VALGRIND_OPTIONS --error-limit=no"
#VALGRIND_OPTIONS="$VALGRIND_OPTIONS --leak-check=full --leak-resolution=high"
#VALGRIND_OPTIONS="$VALGRIND_OPTIONS --show-leak-kinds=all -v"
#VALGRIND_OPTIONS="$VALGRIND_OPTIONS --log-file=/tmp/hardour-%p.log"

TOP=`dirname "$0"`/..
. $TOP/build/gtk2_ardour/ardev_common_waf.sh
if uname | grep -q arwin; then
	OBJSUPP="--suppressions=${TOP}/tools/objc.supp"
fi
export ARDOUR_RUNNING_UNDER_VALGRIND=TRUE
exec valgrind --tool=memcheck \
	$VALGRIND_OPTIONS \
	--track-origins=yes \
	--suppressions=${TOP}/tools/valgrind.supp \
	$OBJSUPP \
	$TOP/build/headless/hardour-$ARDOURVERSION --novst "$@"
