if GTKMM_ATKMM_ENABLED
ATKMMINC = -I$(top_builddir)/atk -I$(top_srcdir)/atk
endif

INCLUDES = \
	-I$(top_builddir)/pango	-I$(top_srcdir)/pango	\
	$(ATKMMINC)	\
	-I$(top_builddir)/gdk	-I$(top_srcdir)/gdk	\
	-I$(top_builddir)/gtk	-I$(top_srcdir)/gtk	\
	$(GTKMM_CFLAGS) $(GTHREAD_CFLAGS)

if GTKMM_ATKMM_ENABLED
ATKMMLIB = $(local_atkmm_lib)
endif

LIBS = \
	$(top_builddir)/pango/pangomm/libpangomm-1.4.la	\
	$(ATKMMLIB)	\
	$(top_builddir)/gdk/gdkmm/libgdkmm-2.4.la	\
	$(top_builddir)/gtk/gtkmm/libgtkmm-2.4.la	\
	$(GTKMM_LIBS)

