#!/usr/bin/env python
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            faderport.cc
            gui.cc
            faderport_interface.cc
            operations.cc
    '''
    obj.defines      = [ 'PACKAGE="ardour_faderport"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = [ '.', './faderport']
    obj.name         = 'libardour_faderport'
    obj.target       = 'ardour_faderport'
    obj.uselib       = 'XML OSX PANGOMM'
    obj.use          = 'libardour libardour_cp libardour_midisurface libgtkmm2ext libpbd'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')
    if bld.is_defined('YTK'):
        obj.use    += ' libytkmm'
        obj.uselib += ' GLIBMM GIOMM'
    else:
        obj.uselib += ' GTKMM'
