#!/usr/bin/python

import os

top = '.'
out = 'build'

def configure(conf):
    pass

def build(bld):
    presets = bld.path.ant_glob ('*.preset')
    formats = bld.path.ant_glob ('*.format')
    bld.install_files (os.path.join(bld.env['DATADIR'], 'export'),
                      presets + formats)

def options(opt):
    pass
