#!/bin/sh

#
# this script copies the relevant files from $1 into this
# working copy of the repository, adds new files and
# prints a list of mods for SConscript
#

from=$1
#strip=`dirname $1`
strip=$1

echo "Looking for copies in $from ... will strip $strip"

for file in `find $from \( -name \*.cpp -o -name \*.h -o -name \*.c \)`
do
  src=$file
  copy=`echo $file | sed "s?$strip/??"`
  echo "Look for $copy"
  if [ -f $copy ] ; then
      cp $src $copy
      echo "copy $copy"
  else
      echo "ADD $copy"
      cp $src $copy
      svn add $copy
  fi
done