#!/usr/bin/env python
import autowaf
import glob
import os

# Version of this package (even if built as a child)
LIBRUBBERBAND_VERSION = '0.0.0'

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBRUBBERBAND_LIB_VERSION = '4.1.0'

# Variables for 'waf dist'
APPNAME = 'librubberband'
VERSION = LIBRUBBERBAND_VERSION

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
	autowaf.set_options(opt)

def configure(conf):
	autowaf.configure(conf)
	conf.check_tool('compiler_cxx')

def build(bld):
	# Library
	obj = bld.new_task_gen('cxx', 'shlib')
	prefix = 'libs/rubberband/'
	sources = glob.glob(prefix + 'src/*.cpp')
	obj.source = [ ]
	for i in sources:
		obj.source += [ i.replace(prefix, '') ]
	obj.export_incdirs = ['.']
	obj.includes     = ['.', 'rubberband']
	obj.name         = 'librubberband'
	obj.target       = 'rubberband'
	obj.uselib       = 'FFTW3 FFTW3F SAMPLERATE SNDFILE'
	obj.uselib_local = 'libvamphost'
	obj.vnum         = LIBRUBBERBAND_LIB_VERSION
	obj.install_path = os.path.join(bld.env['LIBDIR'], 'ardour3')
	obj.cxxflags     = '-DPACKAGE="librubberband"'

def shutdown():
	autowaf.shutdown()

