#!/bin/sh
TOP=`dirname "$0"`/..
. $TOP/build/gtk2_ardour/ardev_common_waf.sh
LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export ARDOUR_RUNNING_UNDER_VALGRIND=TRUE
exec valgrind \
	--error-limit=no --num-callers=50 \
	--tool=callgrind \
	--separate-callers=3 \
	--separate-threads=yes \
	--collect-systime=yes \
	--collect-jumps=yes \
	--instr-atstart=no \
	$TOP/$EXECUTABLE --novst "$@"
