COLOR_ALIAS(ActiveCrossfade,"active crossfade","color 1")
COLOR_ALIAS(ArrangeBase,"arrange base","color 2")
COLOR_ALIAS(AudioBusBase,"audio bus base","color 3")
COLOR_ALIAS(AudioMasterBusBase,"audio master bus base","color 4")
COLOR_ALIAS(AudioTrackBase,"audio track base","color 5")
COLOR_ALIAS(AutomationLine,"automation line","color 6")
COLOR_ALIAS(AutomationTrackFill,"automation track fill","color 5")
COLOR_ALIAS(AutomationTrackOutline,"automation track outline","color 7")
COLOR_ALIAS(BigClockActiveBackground,"big clock active: background","color 4")
COLOR_ALIAS(BigClockActiveCursor,"big clock active: cursor","color 8")
COLOR_ALIAS(BigClockActiveEditedText,"big clock active: edited text","color 8")
COLOR_ALIAS(BigClockActiveText,"big clock active: text","color 9")
COLOR_ALIAS(BigClockBackground,"big clock: background","color 4")
COLOR_ALIAS(BigClockCursor,"big clock: cursor","color 8")
COLOR_ALIAS(BigClockEditedText,"big clock: edited text","color 8")
COLOR_ALIAS(BigClockText,"big clock: text","color 10")
COLOR_ALIAS(ButtonBorder,"border color","color 4")
COLOR_ALIAS(CDMarkerBar,"cd marker bar","color 11")
COLOR_ALIAS(WaveFormClip,"clipped waveform","color 9")
COLOR_ALIAS(GenericClockBackground,"clock: background","color 4")
COLOR_ALIAS(GenericClockCursor,"clock: cursor","color 8")
COLOR_ALIAS(GenericClockEditedText,"clock: edited text","color 8")
COLOR_ALIAS(GenericClockText,"clock: text","color 12")
COLOR_ALIAS(ControlPointFill,"control point fill","color 13")
COLOR_ALIAS(ControlPointOutline,"control point outline","color 9")
COLOR_ALIAS(ControlPointSelected,"control point selected","color 14")
COLOR_ALIAS(CrossfadeEditorBase,"crossfade editor base","color 15")
COLOR_ALIAS(CrossfadeEditorLine,"crossfade editor line","color 4")
COLOR_ALIAS(CrossfadeEditorLineShading,"crossfade editor line shading","color 16")
COLOR_ALIAS(CrossfadeEditorPointFill,"crossfade editor point fill","color 17")
COLOR_ALIAS(CrossfadeEditorPointOutline,"crossfade editor point outline","color 18")
COLOR_ALIAS(CrossfadeEditorWave,"crossfade editor wave","color 13")
COLOR_ALIAS(CrossfadeLine,"crossfade line","color 4")
COLOR_ALIAS(EditPoint,"edit point","color 18")
COLOR_ALIAS(EnteredAutomationLine,"entered automation line","color 19")
COLOR_ALIAS(EnteredGainLine,"entered gain line","color 19")
COLOR_ALIAS(EnteredMarker,"entered marker","color 19")
COLOR_ALIAS(FeedbackAlertFillActive,"feedback alert: fill","color 20")
COLOR_ALIAS(FeedbackAlertFill,"feedback alert: fill active","color 9")
COLOR_ALIAS(FeedbackAlertLEDActive,"feedback alert: led","color 4")
COLOR_ALIAS(FeedbackAlertLED,"feedback alert: led active","color 4")
COLOR_ALIAS(FeedbackAlertTextActive,"feedback alert: text","color 21")
COLOR_ALIAS(FeedbackAlertText,"feedback alert: text active","color 22")
COLOR_ALIAS(FrameHandle,"frame handle","color 23")
COLOR_ALIAS(GainLine,"gain line","color 6")
COLOR_ALIAS(GainLineInactive,"gain line inactive","color 24")
COLOR_ALIAS(GenericButtonFillActive,"generic button: fill","color 25")
COLOR_ALIAS(GenericButtonFill,"generic button: fill active","color 9")
COLOR_ALIAS(GenericButtonLEDActive,"generic button: led","color 15")
COLOR_ALIAS(GenericButtonLED,"generic button: led active","color 18")
COLOR_ALIAS(GenericButtonTextActive,"generic button: text","color 26")
COLOR_ALIAS(GenericButtonText,"generic button: text active","color 27")
COLOR_ALIAS(GhostTrackBase,"ghost track base","color 28")
COLOR_ALIAS(GhostTrackMidiOutline,"ghost track midi outline","color 4")
COLOR_ALIAS(GhostTrackWaveClip,"ghost track wave","color 29")
COLOR_ALIAS(GhostTrackWave,"ghost track wave clip","color 29")
COLOR_ALIAS(GhostTrackWaveFill,"ghost track wave fill","color 29")
COLOR_ALIAS(GhostTrackZeroLine,"ghost track zero line","color 30")
COLOR_ALIAS(ImageTrack,"image track","color 31")
COLOR_ALIAS(InactiveCrossfade,"inactive crossfade","color 32")
COLOR_ALIAS(InactiveFadeHandle,"inactive fade handle","color 33")
COLOR_ALIAS(InactiveGroupTab,"inactive group tab","color 34")
COLOR_ALIAS(InvertButtonFillActive,"invert button: fill","color 25")
COLOR_ALIAS(InvertButtonFill,"invert button: fill active","color 35")
COLOR_ALIAS(InvertButtonLEDActive,"invert button: led","color 36")
COLOR_ALIAS(InvertButtonLED,"invert button: led active","color 37")
COLOR_ALIAS(InvertButtonTextActive,"invert button: text","color 26")
COLOR_ALIAS(InvertButtonText,"invert button: text active","color 33")
COLOR_ALIAS(LocationCDMarker,"location cd marker","color 38")
COLOR_ALIAS(LocationLoop,"location loop","color 39")
COLOR_ALIAS(LocationMarker,"location marker","color 32")
COLOR_ALIAS(LocationPunch,"location punch","color 40")
COLOR_ALIAS(LocationRange,"location range","color 41")
COLOR_ALIAS(LockButtonFillActive,"lock button: fill","color 25")
COLOR_ALIAS(LockButtonFill,"lock button: fill active","color 42")
COLOR_ALIAS(LockButtonLEDActive,"lock button: led","color 4")
COLOR_ALIAS(LockButtonLED,"lock button: led active","color 4")
COLOR_ALIAS(LockButtonTextActive,"lock button: text","color 43")
COLOR_ALIAS(LockButtonText,"lock button: text active","color 26")
COLOR_ALIAS(MarkerBar,"marker bar","color 11")
COLOR_ALIAS(MarkerBarSeparator,"marker bar separator","color 2")
COLOR_ALIAS(MarkerDragLine,"marker drag line","color 44")
COLOR_ALIAS(MarkerLabel,"marker label","color 4")
COLOR_ALIAS(MarkerTrack,"marker track","color 31")
COLOR_ALIAS(MeasureLineBar,"measure line bar","color 13")
COLOR_ALIAS(MeasureLineBeat,"measure line beat","color 45")
COLOR_ALIAS(MeterBackgroundBot,"meter background: bottom","color 46")
COLOR_ALIAS(MeterBackgroundTop,"meter background: top","color 34")
COLOR_ALIAS(MeterBar,"meter bar","color 25")
COLOR_ALIAS(MeterBridgeLabelFillActive,"meter color BBC","color 8")
COLOR_ALIAS(MeterBridgeLabelFill,"meter fill: 0","color 47")
COLOR_ALIAS(MeterBridgeLabelLEDActive,"meter fill: 1","color 48")
COLOR_ALIAS(MeterBridgeLabelLED,"meter fill: 2","color 17")
COLOR_ALIAS(MeterBridgeLabelTextActive,"meter fill: 3","color 17")
COLOR_ALIAS(MeterBridgeLabelText,"meter fill: 4","color 32")
COLOR_ALIAS(MeterBridgePeakIndicatorFillActive,"meter fill: 5","color 32")
COLOR_ALIAS(MeterBridgePeakIndicatorFill,"meter fill: 6","color 8")
COLOR_ALIAS(MeterBridgePeakIndicatorLEDActive,"meter fill: 7","color 8")
COLOR_ALIAS(MeterBridgePeakIndicatorLED,"meter fill: 8","color 9")
COLOR_ALIAS(MeterBridgePeakIndicatorTextActive,"meter fill: 9","color 9")
COLOR_ALIAS(MeterBridgePeakIndicatorText,"meter marker","color 19")
COLOR_ALIAS(MeterBridgePeakLabel,"meterbridge label: fill","color 34")
COLOR_ALIAS(MeterColorBBC,"meterbridge label: fill active","color 46")
COLOR_ALIAS(MeterColor0,"meterbridge label: led","color 9")
COLOR_ALIAS(MeterColor1,"meterbridge label: led active","color 9")
COLOR_ALIAS(MeterColor2,"meterbridge label: text","color 26")
COLOR_ALIAS(MeterColor3,"meterbridge label: text active","color 9")
COLOR_ALIAS(MeterColor4,"meterbridge peakindicator: fill","color 34")
COLOR_ALIAS(MeterColor5,"meterbridge peakindicator: fill active","color 9")
COLOR_ALIAS(MeterColor6,"meterbridge peakindicator: led","color 9")
COLOR_ALIAS(MeterColor7,"meterbridge peakindicator: led active","color 9")
COLOR_ALIAS(MeterColor8,"meterbridge peakindicator: text","color 9")
COLOR_ALIAS(MeterColor9,"meterbridge peakindicator: text active","color 9")
COLOR_ALIAS(MeterMarker,"meterbridge peaklabel","color 9")
COLOR_ALIAS(MidiBusBase,"midi bus base","color 4")
COLOR_ALIAS(MidiDeviceButtonFillActive,"midi device: fill","color 25")
COLOR_ALIAS(MidiDeviceButtonFill,"midi device: fill active","color 42")
COLOR_ALIAS(MidiDeviceButtonLEDActive,"midi device: led","color 49")
COLOR_ALIAS(MidiDeviceButtonLED,"midi device: led active","color 17")
COLOR_ALIAS(MidiDeviceButtonTextActive,"midi device: text","color 26")
COLOR_ALIAS(MidiDeviceButtonText,"midi device: text active","color 50")
COLOR_ALIAS(MidiFrameBase,"midi frame base","color 51")
COLOR_ALIAS(MidiInputButtonFillActive,"midi input button: fill","color 25")
COLOR_ALIAS(MidiInputButtonFill,"midi input button: fill active","color 48")
COLOR_ALIAS(MidiInputButtonLEDActive,"midi input button: led","color 4")
COLOR_ALIAS(MidiInputButtonLED,"midi input button: led active","color 4")
COLOR_ALIAS(MidiInputButtonTextActive,"midi input button: text","color 4")
COLOR_ALIAS(MidiInputButtonText,"midi input button: text active","color 4")
COLOR_ALIAS(MidiMeterColor0,"midi meter fill: 0","color 52")
COLOR_ALIAS(MidiMeterColor1,"midi meter fill: 1","color 53")
COLOR_ALIAS(MidiMeterColor2,"midi meter fill: 2","color 53")
COLOR_ALIAS(MidiMeterColor3,"midi meter fill: 3","color 54")
COLOR_ALIAS(MidiMeterColor4,"midi meter fill: 4","color 54")
COLOR_ALIAS(MidiMeterColor5,"midi meter fill: 5","color 55")
COLOR_ALIAS(MidiMeterColor6,"midi meter fill: 6","color 55")
COLOR_ALIAS(MidiMeterColor7,"midi meter fill: 7","color 56")
COLOR_ALIAS(MidiMeterColor8,"midi meter fill: 8","color 56")
COLOR_ALIAS(MidiMeterColor9,"midi meter fill: 9","color 17")
COLOR_ALIAS(MidiNoteColorTop,"midi note color max","color 52")
COLOR_ALIAS(MidiNoteColorMid,"midi note color mid","color 57")
COLOR_ALIAS(MidiNoteColorBase,"midi note color min","color 58")
COLOR_ALIAS(MidiNoteInactiveChannel,"midi note inactive channel","color 4")
COLOR_ALIAS(MidiNoteSelected,"midi note selected","color 59")
COLOR_ALIAS(MidiNoteVelocityText,"midi note velocity text","color 32")
COLOR_ALIAS(MidiPatchChangeFill,"midi patch change fill","color 60")
COLOR_ALIAS(MidiPatchChangeInactiveChannelFill,"midi patch change inactive channel fill","color 60")
COLOR_ALIAS(MidiPatchChangeInactiveChannelOutline,"midi patch change inactive channel outline","color 61")
COLOR_ALIAS(MidiPatchChangeOutline,"midi patch change outline","color 26")
COLOR_ALIAS(MidiSelectRectFill,"midi select rect fill","color 62")
COLOR_ALIAS(MidiSelectRectOutline,"midi select rect outline","color 63")
COLOR_ALIAS(MidiSysExFill,"midi sysex fill","color 32")
COLOR_ALIAS(MidiSysExOutline,"midi sysex outline","color 64")
COLOR_ALIAS(MidiTrackBase,"midi track base","color 65")
COLOR_ALIAS(MixerStripButtonFillActive,"mixer strip button: fill","color 25")
COLOR_ALIAS(MixerStripButtonFill,"mixer strip button: fill active","color 8")
COLOR_ALIAS(MixerStripButtonLEDActive,"mixer strip button: led","color 66")
COLOR_ALIAS(MixerStripButtonLED,"mixer strip button: led active","color 8")
COLOR_ALIAS(MixerStripButtonTextActive,"mixer strip button: text","color 26")
COLOR_ALIAS(MixerStripButtonText,"mixer strip button: text active","color 4")
COLOR_ALIAS(MixerStripNameButtonFillActive,"mixer strip name button: fill","color 25")
COLOR_ALIAS(MixerStripNameButtonFill,"mixer strip name button: fill active","color 67")
COLOR_ALIAS(MixerStripNameButtonLEDActive,"mixer strip name button: led","color 66")
COLOR_ALIAS(MixerStripNameButtonLED,"mixer strip name button: led active","color 8")
COLOR_ALIAS(MixerStripNameButtonTextActive,"mixer strip name button: text","color 26")
COLOR_ALIAS(MixerStripNameButtonText,"mixer strip name button: text active","color 26")
COLOR_ALIAS(MonitorButtonFillActive,"monitor button: fill","color 25")
COLOR_ALIAS(MonitorButtonFill,"monitor button: fill active","color 68")
COLOR_ALIAS(MonitorButtonLEDActive,"monitor button: led","color 69")
COLOR_ALIAS(MonitorButtonLED,"monitor button: led active","color 9")
COLOR_ALIAS(MonitorButtonTextActive,"monitor button: text","color 26")
COLOR_ALIAS(MonitorButtonText,"monitor button: text active","color 27")
COLOR_ALIAS(MonitorKnobArcEnd,"monitor knob","color 60")
COLOR_ALIAS(MonitorKnobArcStart,"monitor knob: arc end","color 70")
COLOR_ALIAS(MonitorSectionKnob,"monitor knob: arc start","color 16")
COLOR_ALIAS(MonitorSectionCutButtonFillActive,"monitor section cut: fill","color 71")
COLOR_ALIAS(MonitorSectionCutButtonFill,"monitor section cut: fill active","color 8")
COLOR_ALIAS(MonitorSectionCutButtonLEDActive,"monitor section cut: led","color 36")
COLOR_ALIAS(MonitorSectionCutButtonLED,"monitor section cut: led active","color 37")
COLOR_ALIAS(MonitorSectionCutButtonTextActive,"monitor section cut: text","color 26")
COLOR_ALIAS(MonitorSectionCutButtonText,"monitor section cut: text active","color 4")
COLOR_ALIAS(MonitorSectionDimButtonFillActive,"monitor section dim: fill","color 71")
COLOR_ALIAS(MonitorSectionDimButtonFill,"monitor section dim: fill active","color 72")
COLOR_ALIAS(MonitorSectionDimButtonLEDActive,"monitor section dim: led","color 4")
COLOR_ALIAS(MonitorSectionDimButtonLED,"monitor section dim: led active","color 37")
COLOR_ALIAS(MonitorSectionDimButtonTextActive,"monitor section dim: text","color 26")
COLOR_ALIAS(MonitorSectionDimButtonText,"monitor section dim: text active","color 26")
COLOR_ALIAS(MonitorSectionInvertButtonFillActive,"monitor section invert: fill","color 71")
COLOR_ALIAS(MonitorSectionInvertButtonFill,"monitor section invert: fill active","color 35")
COLOR_ALIAS(MonitorSectionInvertButtonLEDActive,"monitor section invert: led","color 36")
COLOR_ALIAS(MonitorSectionInvertButtonLED,"monitor section invert: led active","color 37")
COLOR_ALIAS(MonitorSectionInvertButtonTextActive,"monitor section invert: text","color 4")
COLOR_ALIAS(MonitorSectionInvertButtonText,"monitor section invert: text active","color 4")
COLOR_ALIAS(MonitorSectionMonoButtonFillActive,"monitor section mono: fill","color 71")
COLOR_ALIAS(MonitorSectionMonoButtonFill,"monitor section mono: fill active","color 73")
COLOR_ALIAS(MonitorSectionMonoButtonLEDActive,"monitor section mono: led","color 36")
COLOR_ALIAS(MonitorSectionMonoButtonLED,"monitor section mono: led active","color 37")
COLOR_ALIAS(MonitorSectionMonoButtonTextActive,"monitor section mono: text","color 26")
COLOR_ALIAS(MonitorSectionMonoButtonText,"monitor section mono: text active","color 26")
COLOR_ALIAS(MonitorSectionSoloButtonFillActive,"monitor section solo model: fill","color 71")
COLOR_ALIAS(MonitorSectionSoloButtonFill,"monitor section solo model: fill active","color 42")
COLOR_ALIAS(MonitorSectionSoloButtonLEDActive,"monitor section solo model: led","color 66")
COLOR_ALIAS(MonitorSectionSoloButtonLED,"monitor section solo model: led active","color 8")
COLOR_ALIAS(MonitorSectionSoloModelButtonFillActive,"monitor section solo model: text","color 26")
COLOR_ALIAS(MonitorSectionSoloModelButtonFill,"monitor section solo model: text active","color 26")
COLOR_ALIAS(MonitorSectionSoloModelButtonLEDActive,"monitor section solo: fill","color 71")
COLOR_ALIAS(MonitorSectionSoloModelButtonLED,"monitor section solo: fill active","color 12")
COLOR_ALIAS(MonitorSectionSoloModelButtonTextActive,"monitor section solo: led","color 36")
COLOR_ALIAS(MonitorSectionSoloModelButtonText,"monitor section solo: led active","color 8")
COLOR_ALIAS(MonitorSectionSoloButtonTextActive,"monitor section solo: text","color 4")
COLOR_ALIAS(MonitorSectionSoloButtonText,"monitor section solo: text active","color 4")
COLOR_ALIAS(MonitorSectionSoloExclusiveButtonFillActive,"monitor solo exclusive: fill","color 71")
COLOR_ALIAS(MonitorSectionSoloExclusiveButtonFill,"monitor solo exclusive: fill active","color 20")
COLOR_ALIAS(MonitorSectionSoloExclusiveButtonLEDActive,"monitor solo exclusive: led","color 66")
COLOR_ALIAS(MonitorSectionSoloExclusiveButtonLED,"monitor solo exclusive: led active","color 8")
COLOR_ALIAS(MonitorSectionSoloExclusiveButtonTextActive,"monitor solo exclusive: text","color 26")
COLOR_ALIAS(MonitorSectionSoloExclusiveButtonText,"monitor solo exclusive: text active","color 26")
COLOR_ALIAS(MonitorSectionSoloOverrideButtonFillActive,"monitor solo override: fill","color 71")
COLOR_ALIAS(MonitorSectionSoloOverrideButtonFill,"monitor solo override: fill active","color 42")
COLOR_ALIAS(MonitorSectionSoloOverrideButtonLEDActive,"monitor solo override: led","color 66")
COLOR_ALIAS(MonitorSectionSoloOverrideButtonLED,"monitor solo override: led active","color 8")
COLOR_ALIAS(MonitorSectionSoloOverrideButtonTextActive,"monitor solo override: text","color 26")
COLOR_ALIAS(MonitorSectionSoloOverrideButtonText,"monitor solo override: text active","color 26")
COLOR_ALIAS(MonoPannerBackground,"mono panner bg","color 61")
COLOR_ALIAS(MonoPannerFill,"mono panner fill","color 74")
COLOR_ALIAS(MonoPannerOutline,"mono panner outline","color 70")
COLOR_ALIAS(MonoPannerPositionFill,"mono panner position fill","color 11")
COLOR_ALIAS(MonoPannerPositionOutline,"mono panner position outline","color 70")
COLOR_ALIAS(MonoPannerText,"mono panner text","color 4")
COLOR_ALIAS(MouseModeButtonFillActive,"mouse mode button: fill","color 25")
COLOR_ALIAS(MouseModeButtonFill,"mouse mode button: fill active","color 12")
COLOR_ALIAS(MouseModeButtonLEDActive,"mouse mode button: led","color 66")
COLOR_ALIAS(MouseModeButtonLED,"mouse mode button: led active","color 8")
COLOR_ALIAS(MouseModeButtonTextActive,"mouse mode button: text","color 26")
COLOR_ALIAS(MouseModeButtonText,"mouse mode button: text active","color 4")
COLOR_ALIAS(MuteButtonFillActive,"mute button: fill","color 25")
COLOR_ALIAS(MuteButtonFill,"mute button: fill active","color 75")
COLOR_ALIAS(MuteButtonLEDActive,"mute button: led","color 4")
COLOR_ALIAS(MuteButtonLED,"mute button: led active","color 4")
COLOR_ALIAS(MuteButtonTextActive,"mute button: text","color 26")
COLOR_ALIAS(MuteButtonText,"mute button: text active","color 27")
COLOR_ALIAS(NameHighlightFill,"name highlight fill","color 18")
COLOR_ALIAS(NameHighlightOutline,"name highlight outline","color 23")
COLOR_ALIAS(NudgeButtonFillActive,"nudge button: fill","color 20")
COLOR_ALIAS(NudgeButtonFill,"nudge button: fill active","color 42")
COLOR_ALIAS(NudgeButtonLEDActive,"nudge button: led","color 66")
COLOR_ALIAS(NudgeButtonLED,"nudge button: led active","color 8")
COLOR_ALIAS(NudgeButtonTextActive,"nudge button: text","color 26")
COLOR_ALIAS(NudgeButtonText,"nudge button: text active","color 26")
COLOR_ALIAS(NudgeClockBackground,"nudge clock: background","color 7")
COLOR_ALIAS(NudgeClockCursor,"nudge clock: cursor","color 8")
COLOR_ALIAS(NudgeClockEditedText,"nudge clock: edited text","color 8")
COLOR_ALIAS(NudgeClockText,"nudge clock: text","color 12")
COLOR_ALIAS(PianoRollBlack,"piano roll black","color 76")
COLOR_ALIAS(PianoRollBlackOutline,"piano roll black outline","color 10")
COLOR_ALIAS(PianoRollWhite,"piano roll white","color 45")
COLOR_ALIAS(PlayHead,"play head","color 9")
COLOR_ALIAS(PluginBypassButtonFillActive,"plugin bypass button: fill","color 71")
COLOR_ALIAS(PluginBypassButtonFill,"plugin bypass button: fill active","color 42")
COLOR_ALIAS(PluginBypassButtonLEDActive,"plugin bypass button: led","color 69")
COLOR_ALIAS(PluginBypassButtonLED,"plugin bypass button: led active","color 9")
COLOR_ALIAS(PluginBypassButtonTextActive,"plugin bypass button: text","color 26")
COLOR_ALIAS(PluginBypassButtonText,"plugin bypass button: text active","color 26")
COLOR_ALIAS(ProcessorAutomationLine,"processor automation line","color 77")
COLOR_ALIAS(ProcessorControlButtonFillActive,"processor control button: fill","color 29")
COLOR_ALIAS(ProcessorControlButtonFill,"processor control button: fill active","color 46")
COLOR_ALIAS(ProcessorControlButtonLEDActive,"processor control button: led","color 67")
COLOR_ALIAS(ProcessorControlButtonLED,"processor control button: led active","color 16")
COLOR_ALIAS(ProcessorControlButtonTextActive,"processor control button: text","color 13")
COLOR_ALIAS(ProcessorControlButtonText,"processor control button: text active","color 13")
COLOR_ALIAS(ProcessorFaderFillActive,"processor fader: fill","color 16")
COLOR_ALIAS(ProcessorFaderFill,"processor fader: fill active","color 78")
COLOR_ALIAS(ProcessorFaderLEDActive,"processor fader: led","color 44")
COLOR_ALIAS(ProcessorFaderLED,"processor fader: led active","color 37")
COLOR_ALIAS(ProcessorFaderTextActive,"processor fader: text","color 45")
COLOR_ALIAS(ProcessorFaderText,"processor fader: text active","color 50")
COLOR_ALIAS(ProcessorPostFaderFillActive,"processor postfader: fill","color 58")
COLOR_ALIAS(ProcessorPostFaderFill,"processor postfader: fill active","color 79")
COLOR_ALIAS(ProcessorPostFaderLEDActive,"processor postfader: led","color 44")
COLOR_ALIAS(ProcessorPostFaderLED,"processor postfader: led active","color 37")
COLOR_ALIAS(ProcessorPostFaderTextActive,"processor postfader: text","color 45")
COLOR_ALIAS(ProcessorPostFaderText,"processor postfader: text active","color 50")
COLOR_ALIAS(ProcessorPreFaderFillActive,"processor prefader: fill","color 40")
COLOR_ALIAS(ProcessorPreFaderFill,"processor prefader: fill active","color 80")
COLOR_ALIAS(ProcessorPreFaderLEDActive,"processor prefader: led","color 44")
COLOR_ALIAS(ProcessorPreFaderLED,"processor prefader: led active","color 37")
COLOR_ALIAS(ProcessorPreFaderTextActive,"processor prefader: text","color 45")
COLOR_ALIAS(ProcessorPreFaderText,"processor prefader: text active","color 50")
COLOR_ALIAS(PunchButtonFillActive,"punch button: fill","color 20")
COLOR_ALIAS(PunchButtonFill,"punch button: fill active","color 9")
COLOR_ALIAS(PunchButtonLEDActive,"punch button: led","color 4")
COLOR_ALIAS(PunchButtonLED,"punch button: led active","color 4")
COLOR_ALIAS(PunchButtonTextActive,"punch button: text","color 81")
COLOR_ALIAS(PunchButtonText,"punch button: text active","color 82")
COLOR_ALIAS(PunchClockBackground,"punch clock: background","color 4")
COLOR_ALIAS(PunchClockCursor,"punch clock: cursor","color 9")
COLOR_ALIAS(PunchClockEditedText,"punch clock: edited text","color 9")
COLOR_ALIAS(PunchClockText,"punch clock: text","color 12")
COLOR_ALIAS(PunchLine,"punch line","color 83")
COLOR_ALIAS(RangeDragBarRect,"range drag bar rect","color 21")
COLOR_ALIAS(RangeDragRect,"range drag rect","color 56")
COLOR_ALIAS(RangeMarkerBar,"range marker bar","color 3")
COLOR_ALIAS(RecWaveFormFill,"record enable button: fill","color 25")
COLOR_ALIAS(RecWaveForm,"record enable button: fill active","color 83")
COLOR_ALIAS(RecEnableButtonFillActive,"record enable button: led","color 84")
COLOR_ALIAS(RecEnableButtonFill,"record enable button: led active","color 85")
COLOR_ALIAS(RecEnableButtonLEDActive,"record enable button: text","color 81")
COLOR_ALIAS(RecEnableButtonLED,"record enable button: text active","color 4")
COLOR_ALIAS(RecEnableButtonTextActive,"recorded waveform fill","color 13")
COLOR_ALIAS(RecEnableButtonText,"recorded waveform outline","color 43")
COLOR_ALIAS(RecordingRect,"recording rect","color 86")
COLOR_ALIAS(CoveredRegion,"region area covered by another region","color 87")
COLOR_ALIAS(FrameBase,"region base","color 11")
COLOR_ALIAS(RouteButtonFillActive,"route button: fill","color 25")
COLOR_ALIAS(RouteButtonFill,"route button: fill active","color 67")
COLOR_ALIAS(RouteButtonLEDActive,"route button: led","color 66")
COLOR_ALIAS(RouteButtonLED,"route button: led active","color 8")
COLOR_ALIAS(RouteButtonTextActive,"route button: text","color 26")
COLOR_ALIAS(RouteButtonText,"route button: text active","color 27")
COLOR_ALIAS(RubberBandRect,"rubber band rect","color 88")
COLOR_ALIAS(RudeAuditionFillActive,"rude audition: fill","color 20")
COLOR_ALIAS(RudeAuditionFill,"rude audition: fill active","color 86")
COLOR_ALIAS(RudeAuditionLEDActive,"rude audition: led","color 4")
COLOR_ALIAS(RudeAuditionLED,"rude audition: led active","color 4")
COLOR_ALIAS(RudeAuditionTextActive,"rude audition: text","color 21")
COLOR_ALIAS(RudeAuditionText,"rude audition: text active","color 13")
COLOR_ALIAS(RudeIsolateFillActive,"rude isolate: fill","color 42")
COLOR_ALIAS(RudeIsolateFill,"rude isolate: fill active","color 89")
COLOR_ALIAS(RudeIsolateLEDActive,"rude isolate: led","color 4")
COLOR_ALIAS(RudeIsolateLED,"rude isolate: led active","color 4")
COLOR_ALIAS(RudeIsolateTextActive,"rude isolate: text","color 21")
COLOR_ALIAS(RudeIsolateText,"rude isolate: text active","color 4")
COLOR_ALIAS(RudeSoloFillActive,"rude solo: fill","color 20")
COLOR_ALIAS(RudeSoloFill,"rude solo: fill active","color 86")
COLOR_ALIAS(RudeSoloLEDActive,"rude solo: led","color 4")
COLOR_ALIAS(RudeSoloLED,"rude solo: led active","color 4")
COLOR_ALIAS(RudeSoloTextActive,"rude solo: text","color 21")
COLOR_ALIAS(RudeSoloText,"rude solo: text active","color 22")
COLOR_ALIAS(RulerBase,"ruler base","color 90")
COLOR_ALIAS(RulerText,"ruler text","color 22")
COLOR_ALIAS(SecondaryClockBackground,"secondary clock: background","color 7")
COLOR_ALIAS(SecondaryClockCursor,"secondary clock: cursor","color 8")
COLOR_ALIAS(SecondaryClockEditedText,"secondary clock: edited text","color 8")
COLOR_ALIAS(SecondaryClockText,"secondary clock: text","color 91")
COLOR_ALIAS(SecondaryDeltaClockBackground,"secondary delta clock: background","color 4")
COLOR_ALIAS(SecondaryDeltaClockCursor,"secondary delta clock: cursor","color 9")
COLOR_ALIAS(SecondaryDeltaClockEditedText,"secondary delta clock: edited text","color 9")
COLOR_ALIAS(SecondaryDeltaClockText,"secondary delta clock: text","color 92")
COLOR_ALIAS(SelectedCrossfadeEditorLine,"selected crossfade editor line","color 14")
COLOR_ALIAS(SelectedCrossfadeEditorWave,"selected crossfade editor wave","color 32")
COLOR_ALIAS(SelectedCrossfadeEditorWaveFill,"selected crossfade editor wave fill","color 4")
COLOR_ALIAS(SelectedMidiNoteColorTop,"selected midi note color max","color 62")
COLOR_ALIAS(SelectedMidiNoteColorMid,"selected midi note color mid","color 93")
COLOR_ALIAS(SelectedMidiNoteColorBase,"selected midi note color min","color 61")
COLOR_ALIAS(SelectedFrameBase,"selected region base","color 25")
COLOR_ALIAS(SelectedTimeAxisFrame,"selected time axis frame","color 86")
COLOR_ALIAS(SelectedWaveFormFill,"selected waveform fill","color 8")
COLOR_ALIAS(SelectedWaveForm,"selected waveform outline","color 67")
COLOR_ALIAS(SelectionClockBackground,"selection","color 94")
COLOR_ALIAS(SelectionClockCursor,"selection clock: background","color 4")
COLOR_ALIAS(SelectionClockEditedText,"selection clock: cursor","color 9")
COLOR_ALIAS(SelectionClockText,"selection clock: edited text","color 9")
COLOR_ALIAS(Selection,"selection clock: text","color 12")
COLOR_ALIAS(SelectionRect,"selection rect","color 95")
COLOR_ALIAS(SendButtonFillActive,"send alert button: fill","color 71")
COLOR_ALIAS(SendButtonFill,"send alert button: fill active","color 96")
COLOR_ALIAS(SendButtonLEDActive,"send alert button: led","color 4")
COLOR_ALIAS(SendButtonLED,"send alert button: led active","color 4")
COLOR_ALIAS(SendButtonTextActive,"send alert button: text","color 97")
COLOR_ALIAS(SendButtonText,"send alert button: text active","color 4")
COLOR_ALIAS(Shuttle,"shuttle","color 12")
COLOR_ALIAS(Silence,"silence","color 98")
COLOR_ALIAS(SilenceText,"silence text","color 99")
COLOR_ALIAS(SoloButtonFillActive,"solo button: fill","color 25")
COLOR_ALIAS(SoloButtonFill,"solo button: fill active","color 12")
COLOR_ALIAS(SoloButtonLEDActive,"solo button: led","color 4")
COLOR_ALIAS(SoloButtonLED,"solo button: led active","color 4")
COLOR_ALIAS(SoloButtonTextActive,"solo button: text","color 26")
COLOR_ALIAS(SoloButtonText,"solo button: text active","color 27")
COLOR_ALIAS(SoloIsolateButtonFillActive,"solo isolate: fill","color 25")
COLOR_ALIAS(SoloIsolateButtonFill,"solo isolate: fill active","color 42")
COLOR_ALIAS(SoloIsolateButtonLEDActive,"solo isolate: led","color 69")
COLOR_ALIAS(SoloIsolateButtonLED,"solo isolate: led active","color 9")
COLOR_ALIAS(SoloIsolateButtonTextActive,"solo isolate: text","color 26")
COLOR_ALIAS(SoloIsolateButtonText,"solo isolate: text active","color 26")
COLOR_ALIAS(SoloSafeButtonFillActive,"solo safe: fill","color 25")
COLOR_ALIAS(SoloSafeButtonFill,"solo safe: fill active","color 42")
COLOR_ALIAS(SoloSafeButtonLEDActive,"solo safe: led","color 69")
COLOR_ALIAS(SoloSafeButtonLED,"solo safe: led active","color 9")
COLOR_ALIAS(SoloSafeButtonTextActive,"solo safe: text","color 26")
COLOR_ALIAS(SoloSafeButtonText,"solo safe: text active","color 26")
COLOR_ALIAS(StereoPannerBackground,"stereo panner bg","color 61")
COLOR_ALIAS(StereoPannerFill,"stereo panner fill","color 74")
COLOR_ALIAS(StereoPannerInvertedBackground,"stereo panner inverted bg","color 61")
COLOR_ALIAS(StereoPannerInvertedFill,"stereo panner inverted fill","color 100")
COLOR_ALIAS(StereoPannerInvertedOutline,"stereo panner inverted outline","color 83")
COLOR_ALIAS(StereoPannerInvertedText,"stereo panner inverted text","color 4")
COLOR_ALIAS(StereoPannerMonoBackground,"stereo panner mono bg","color 61")
COLOR_ALIAS(StereoPannerMonoFill,"stereo panner mono fill","color 54")
COLOR_ALIAS(StereoPannerMonoOutline,"stereo panner mono outline","color 101")
COLOR_ALIAS(StereoPannerMonoText,"stereo panner mono text","color 4")
COLOR_ALIAS(StereoPannerOutline,"stereo panner outline","color 70")
COLOR_ALIAS(StereoPannerRule,"stereo panner rule","color 70")
COLOR_ALIAS(StereoPannerText,"stereo panner text","color 4")
COLOR_ALIAS(TempoBar,"tempo bar","color 102")
COLOR_ALIAS(TempoMarker,"tempo marker","color 19")
COLOR_ALIAS(TimeAxisFrame,"time axis frame","color 4")
COLOR_ALIAS(TimeStretchFill,"time stretch fill","color 26")
COLOR_ALIAS(TimeStretchOutline,"time stretch outline","color 94")
COLOR_ALIAS(TrackNumberLabelFillActive,"tracknumber label: fill","color 34")
COLOR_ALIAS(TrackNumberLabelFill,"tracknumber label: fill active","color 46")
COLOR_ALIAS(TrackNumberLabelLEDActive,"tracknumber label: led","color 9")
COLOR_ALIAS(TrackNumberLabelLED,"tracknumber label: led active","color 9")
COLOR_ALIAS(TrackNumberLabelTextActive,"tracknumber label: text","color 26")
COLOR_ALIAS(TrackNumberLabelText,"tracknumber label: text active","color 9")
COLOR_ALIAS(TransportActiveOptionButtonFillActive,"transport active option button: fill","color 25")
COLOR_ALIAS(TransportActiveOptionButtonFill,"transport active option button: fill active","color 48")
COLOR_ALIAS(TransportActiveOptionButtonLEDActive,"transport active option button: led","color 66")
COLOR_ALIAS(TransportActiveOptionButtonLED,"transport active option button: led active","color 8")
COLOR_ALIAS(TransportActiveOptionButtonTextActive,"transport active option button: text","color 26")
COLOR_ALIAS(TransportActiveOptionButtonText,"transport active option button: text active","color 4")
COLOR_ALIAS(TransportButtonFillActive,"transport button: fill","color 25")
COLOR_ALIAS(TransportButtonFill,"transport button: fill active","color 48")
COLOR_ALIAS(TransportButtonLEDActive,"transport button: led","color 4")
COLOR_ALIAS(TransportButtonLED,"transport button: led active","color 4")
COLOR_ALIAS(TransportButtonTextActive,"transport button: text","color 4")
COLOR_ALIAS(TransportButtonText,"transport button: text active","color 4")
COLOR_ALIAS(TransportClockBackground,"transport clock: background","color 7")
COLOR_ALIAS(TransportClockCursor,"transport clock: cursor","color 8")
COLOR_ALIAS(TransportClockEditedText,"transport clock: edited text","color 8")
COLOR_ALIAS(TransportClockText,"transport clock: text","color 91")
COLOR_ALIAS(TransportDeltaClockBackground,"transport delta clock: background","color 4")
COLOR_ALIAS(TransportDeltaClockCursor,"transport delta clock: cursor","color 9")
COLOR_ALIAS(TransportDeltaClockEditedText,"transport delta clock: edited text","color 9")
COLOR_ALIAS(TransportDeltaClockText,"transport delta clock: text","color 92")
COLOR_ALIAS(TransportDragRect,"transport drag rect","color 21")
COLOR_ALIAS(TransportLoopRect,"transport loop rect","color 103")
COLOR_ALIAS(TransportMarkerBar,"transport marker bar","color 11")
COLOR_ALIAS(TransportOptionButtonFillActive,"transport option button: fill","color 25")
COLOR_ALIAS(TransportOptionButtonFill,"transport option button: fill active","color 42")
COLOR_ALIAS(TransportOptionButtonLEDActive,"transport option button: led","color 66")
COLOR_ALIAS(TransportOptionButtonLED,"transport option button: led active","color 8")
COLOR_ALIAS(TransportOptionButtonTextActive,"transport option button: text","color 26")
COLOR_ALIAS(TransportOptionButtonText,"transport option button: text active","color 26")
COLOR_ALIAS(TransportPunchRect,"transport punch rect","color 80")
COLOR_ALIAS(TransportRecenableButtonFillActive,"transport recenable button: fill","color 20")
COLOR_ALIAS(TransportRecenableButtonFill,"transport recenable button: fill active","color 83")
COLOR_ALIAS(TransportRecenableButtonLEDActive,"transport recenable button: led","color 4")
COLOR_ALIAS(TransportRecenableButtonLED,"transport recenable button: led active","color 4")
COLOR_ALIAS(TransportRecenableButtonTextActive,"transport recenable button: text","color 4")
COLOR_ALIAS(TransportRecenableButtonText,"transport recenable button: text active","color 4")
COLOR_ALIAS(TrimHandle,"trim handle","color 18")
COLOR_ALIAS(TrimHandleLocked,"trim handle locked","color 86")
COLOR_ALIAS(VerboseCanvasCursor,"verbose canvas cursor","color 32")
COLOR_ALIAS(VestigialFrame,"vestigial frame","color 4")
COLOR_ALIAS(VideoBar,"video timeline bar","color 46")
COLOR_ALIAS(WaveFormFill,"waveform fill","color 13")
COLOR_ALIAS(WaveForm,"waveform outline","color 4")
COLOR_ALIAS(ZeroLine,"zero line","color 104")
COLOR_ALIAS(ZoomButtonFillActive,"zoom button: fill","color 25")
COLOR_ALIAS(ZoomButtonFill,"zoom button: fill active","color 48")
COLOR_ALIAS(ZoomButtonLEDActive,"zoom button: led","color 66")
COLOR_ALIAS(ZoomButtonLED,"zoom button: led active","color 8")
COLOR_ALIAS(ZoomButtonTextActive,"zoom button: text","color 26")
COLOR_ALIAS(ZoomButtonText,"zoom button: text active","color 4")
COLOR_ALIAS(ZoomMenuFillActive,"zoom menu: fill","color 105")
COLOR_ALIAS(ZoomMenuFill,"zoom menu: fill active","color 42")
COLOR_ALIAS(ZoomMenuLEDActive,"zoom menu: led","color 66")
COLOR_ALIAS(ZoomMenuLED,"zoom menu: led active","color 8")
COLOR_ALIAS(ZoomMenuTextActive,"zoom menu: text","color 26")
COLOR_ALIAS(ZoomMenuText,"zoom menu: text active","color 26")
