/*
    Copyright (C) 2000-2007 Paul Davis 

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

*/

#ifndef __ardour_gtk_crossfade_xpms_h_
#define __ardour_gtk_crossfade_xpms_h_

/* XPM */
static const gchar * hiout_xpm[] = {
"25 25 3 1",
" 	c None",
".	c #F6F92A",
"+	c #F6FA2A",
"                         ",
"                         ",
"                         ",
"                         ",
"     .+++++++            ",
"     .++++++++           ",
"          ++++++         ",
"            +++++        ",
"              ++++       ",
"               +++       ",
"                +++      ",
"                +++      ",
"                 +++     ",
"                 +++     ",
"                 +++     ",
"                 +++     ",
"                  ++     ",
"                  +++    ",
"                  +++    ",
"                  +++    ",
"                  +++    ",
"                  .+.    ",
"                         ",
"                         ",
"                         "};
/* XPM */
static const gchar * regout2_xpm[] = {
"25 25 3 1",
" 	c None",
".	c #FDFD00",
"+	c #FEFE00",
"                         ",
"                         ",
"   .+.                   ",
"   +++                   ",
"   +++                   ",
"   +++                   ",
"   .++                   ",
"    ++                   ",
"    ++.                  ",
"    +++                  ",
"    .++                  ",
"     +++                 ",
"      +++                ",
"      .+++               ",
"       ++++              ",
"        ++++             ",
"         +++++.          ",
"          .+++++.        ",
"            .++++++.     ",
"              .+++++     ",
"                 .+.     ",
"                         ",
"                         ",
"                         ",
"                         "};
/* XPM */
static const gchar * regout_xpm[] = {
"25 25 3 1",
" 	c None",
".	c #FDFD00",
"+	c #FEFE00",
"                         ",
"                         ",
"                         ",
"                         ",
"    .++++.               ",
"    .++++++.             ",
"       .+++++.           ",
"         .+++++          ",
"            ++++         ",
"             ++++        ",
"              ++++       ",
"               +++.      ",
"                +++      ",
"                 ++.     ",
"                 +++     ",
"                 .++.    ",
"                  +++    ",
"                  .++    ",
"                   ++    ",
"                   ++    ",
"                   ++    ",
"                   ..    ",
"                         ",
"                         ",
"                         "};
/* XPM */
static const gchar * regin2_xpm[] = {
"25 25 3 1",
" 	c None",
".	c #FDFD00",
"+	c #FEFE00",
"                         ",
"                         ",
"                  .+.    ",
"                  +++    ",
"                  +++    ",
"                  ++.    ",
"                 .++     ",
"                 +++     ",
"                 ++.     ",
"                .++      ",
"                +++      ",
"               .++.      ",
"               +++       ",
"              +++.       ",
"             ++++        ",
"           .++++         ",
"         .+++++          ",
"      .++++++.           ",
"    .++++++.             ",
"    ++++.                ",
"    ..                   ",
"                         ",
"                         ",
"                         ",
"                         "};
/* XPM */
static const gchar * regin_xpm[] = {
"25 25 3 1",
" 	c None",
".	c #FDFD00",
"+	c #FEFE00",
"                         ",
"                         ",
"                         ",
"                         ",
"               .++++.    ",
"             .++++++.    ",
"           .+++++.       ",
"          +++++.         ",
"         ++++            ",
"        ++++             ",
"       ++++              ",
"      .+++               ",
"      +++                ",
"     .++                 ",
"     +++                 ",
"    .++.                 ",
"    +++                  ",
"    ++.                  ",
"    ++                   ",
"    ++                   ",
"    ++                   ",
"    ..                   ",
"                         ",
"                         ",
"                         "};
/* XPM */
static const gchar * linout_xpm[] = {
"25 25 3 1",
" 	c None",
".	c #FDFD00",
"+	c #FEFE00",
"                         ",
"                         ",
"                         ",
"    ..                   ",
"    +++                  ",
"    .+++                 ",
"     ++++                ",
"      ++++               ",
"       +++.              ",
"        +++              ",
"         +++             ",
"          +++            ",
"           +++           ",
"            +++          ",
"             +++         ",
"              +++        ",
"              .+++       ",
"               ++++      ",
"                ++++     ",
"                 ++++    ",
"                  ++++   ",
"                   ..    ",
"                         ",
"                         ",
"                         "};
/* XPM */
static const gchar * linin_xpm[] = {
"25 25 3 1",
" 	c None",
".	c #FDFD00",
"+	c #FEFE00",
"                         ",
"                         ",
"                         ",
"                         ",
"                   .+.   ",
"                  +++.   ",
"                 ++++    ",
"                ++++     ",
"               ++++      ",
"              ++++       ",
"             +++.        ",
"            +++          ",
"           +++           ",
"          +++            ",
"        .+++             ",
"       ++++              ",
"      ++++               ",
"     ++++                ",
"    ++++                 ",
"   .+++                  ",
"   .++                   ",
"    +                    ",
"                         ",
"                         ",
"                         "};
/* XPM */
static const gchar * loout_xpm[] = {
"25 25 3 1",
" 	c None",
".	c #F6F92A",
"+	c #F6FA2A",
"                         ",
"                         ",
"    ..                   ",
"    ++                   ",
"    ++                   ",
"    ++                   ",
"    ++                   ",
"    ++                   ",
"    +++                  ",
"    +++                  ",
"    +++                  ",
"    ++++                 ",
"     +++                 ",
"     +++                 ",
"      +++                ",
"      ++++               ",
"       +++++             ",
"        ++++++           ",
"         +++++++++.      ",
"           ++++++++      ",
"              ++++.      ",
"                         ",
"                         ",
"                         ",
"                         "};
/* XPM */
static const gchar * loin_xpm[] = {
"25 25 3 1",
" 	c None",
".	c #F6F92A",
"+	c #F6FA2A",
"                         ",
"                         ",
"                 .+.     ",
"                 +++     ",
"                 +++     ",
"                 +++     ",
"                 +++     ",
"                 ++      ",
"                +++      ",
"                +++      ",
"                +++      ",
"                +++      ",
"               +++       ",
"               +++       ",
"              +++        ",
"             ++++        ",
"           +++++         ",
"         ++++++          ",
"    .++++++++            ",
"    .+++++++             ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         "};
/* XPM */
static const gchar * hiin_xpm[] = {
"25 25 3 1",
" 	c None",
".	c #F6FA2A",
"+	c #F6F92A",
"                         ",
"                         ",
"                         ",
"                         ",
"            .......+     ",
"           ........+     ",
"         ......          ",
"        .....            ",
"       ....              ",
"       ...               ",
"      ...                ",
"      ...                ",
"     ...                 ",
"     ...                 ",
"     ...                 ",
"     ...                 ",
"     ..                  ",
"    ...                  ",
"    ...                  ",
"    ...                  ",
"    ...                  ",
"    +.+                  ",
"                         ",
"                         ",
"                         "};


#endif /* __ardour_gtk_crossfade_xpms_h_ */
