#!/usr/bin/env python
import os
import re
import shutil
import waflib.extras.autowaf as autowaf
import waflib.Options as Options, waflib.Utils as Utils

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.check_pkg(conf, 'lv2', atleast_version='1.0.0',
                      uselib_store='LV2_1_0_0')
    autowaf.check_pkg(conf, 'cairo', uselib_store='CAIRO', atleast_version='1.12.0') 

def build(bld):
    bundle = 'a-delay.lv2'
    module_pat = re.sub('^lib', '', bld.env.cshlib_PATTERN)
    module_ext = module_pat[module_pat.rfind('.'):]

    # Build RDF files
    for i in ['manifest.ttl', 'a-delay.ttl', 'presets.ttl']:
        obj = bld(features='subst')
        obj.source = i + '.in'
        obj.target = '../../LV2/%s/%s' % (bundle, i)
        obj.install_path = '${LV2DIR}/%s' % bundle
        obj.chmod = Utils.O644
        obj.LIB_EXT = module_ext

    # Build plugin library
    obj = bld(features     = 'c cshlib',
              source       = 'a-delay.c',
              name         = 'a-delay',
              cflags       = [ bld.env['compiler_flags_dict']['pic'],  bld.env['compiler_flags_dict']['c99'] ],
              includes     = [ '../../ardour' ],
              target       = '../../LV2/%s/a-delay' % bundle,
              install_path = '${LV2DIR}/%s' % bundle,
              uselib       = 'CAIRO',
              use          = 'LV2_1_0_0'
              )
    obj.env.cshlib_PATTERN = module_pat
    obj.env.cxxshlib_PATTERN = module_pat

# vi:set ts=4 sw=4 et:
