#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.check_pkg(conf, 'glib-2.0', uselib_store='GLIB', atleast_version='2.73', mandatory=True)
    autowaf.check_pkg(conf, 'glibmm-2.4', uselib_store='GLIBMM', atleast_version='2.32.0', mandatory=True)

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            midi_surface.cc
            midi_byte_array.cc
    '''
    obj.export_includes = ['.']
    obj.defines      = [ 'PACKAGE="ardour_midisurface"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.defines     += [ 'VERSIONSTRING="' + bld.env['VERSION'] + '"' ]
    obj.includes     = ['.', './midi_surface']
    obj.name         = 'libardour_midisurface'
    obj.target       = 'ardour_midisurface'
    obj.uselib       = 'GLIB GLIBMM SIGCPP XML OSX'
    obj.use          = 'libardour libardour_cp libpbd libevoral libmidipp libtemporal'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')

def shutdown():
    autowaf.shutdown()
