# -*- python -*-

import os
import os.path
import glob

atkmm_files = glob.glob('atkmm/*.cc')

Import('env libraries install_prefix')
atkmm = env.Copy()
atkmm.Merge([libraries['glibmm2'], libraries['gtk2'], libraries['sigc2'] ])

libatkmm = atkmm.SharedLibrary('atkmm', atkmm_files)
Default(libatkmm)

env.Alias('install', env.Install(os.path.join(install_prefix, env['LIBDIR'], 'ardour2'), libatkmm))

env.Alias('tarball', env.Distribute (env['DISTTREE'],
                                     [ 'SConscript', 'atkmm.h'] + 
				     atkmm_files + 
				     glob.glob('atkmm/*.h') +
				     glob.glob('atkmm/private/*.h')
				     ))
