import glob

atkmm_files = glob.glob('atkmm/*.cc')

Import('env libraries')
atkmm = env.Copy()
atkmm.Merge([libraries['glibmm2'], libraries['gtk2'], libraries['sigc2'] ])

libatkmm = atkmm.StaticLibrary('atkmm', atkmm_files)
Default(libatkmm)
