jobs:
  include:
    - language: cpp
      dist: bionic
      compiler:
        - gcc
      os:
        - linux
      git:
        depth: false
      install:
        - sudo apt-get update
        - sudo apt-get upgrade
        - sudo apt-get install fftw3-dev libarchive-dev libaubio-dev libboost-all-dev libcppunit-dev libcwiid-dev libglibmm-2.4-dev libgtkmm-2.4-dev libjack-dev liblilv-dev liblo-dev liblrdf-dev libpangomm-1.4-dev librubberband-dev libsamplerate0-dev libserd-dev libsord-dev libsratom-dev libtag1-dev libudev-dev libusb-1.0-0-dev libxml2-dev vamp-plugin-sdk libasound2-dev libsndfile-dev
        - ./waf configure
      script:
        - ./waf
      before_deploy:
      - tar -czvf gtk2_ardour.tar.gz gtk2_ardour
      deploy:
        provider: releases
        token: $GITHUB_AUTH_TOKEN
        skip_cleanup: true
        file: gtk2_ardour.tar.gz
        on:
          tags: true
notifications:
  email: false
