#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import TaskGen
import os
import sys

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    pass

def build(bld):
    if bld.env['build_target'] == 'mingw':
        return
    obj = bld (features = 'c cprogram')
    obj.source = 'exec_wrapper.c'
    obj.target = 'ardour-exec-wrapper'
    obj.install_path = os.path.join(bld.env['LIBDIR'])
    obj.defines = [
            '_POSIX_SOURCE',
            '_XOPEN_SOURCE=500',
    ]
