#!/usr/bin/env python
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    if bld.env['build_target'] == 'mingw':
        return
    obj = bld (features = 'c cprogram')
    obj.source = 'exec_wrapper.c'
    obj.target = 'ardour-exec-wrapper'
    obj.install_path = os.path.join(bld.env['LIBDIR'])
    obj.defines = [
            '_POSIX_SOURCE',
            '_XOPEN_SOURCE=500',
    ]
