#!/usr/bin/env python
import autowaf
import os

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBARDOUR_PAN1IN2OUT_LIB_VERSION = '1.0.0'

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
        autowaf.set_options(opt)

def configure(conf):
        autowaf.configure(conf)

def build(bld):
        obj = bld.new_task_gen('cxx', 'shlib')
        obj.source = [ 'panner_1in2out.cc' ]
        obj.export_incdirs = ['.']
        obj.cxxflags     = '-DPACKAGE="libardour_pan1in2out"'
        obj.includes     = ['.']
        obj.name         = 'libardour_pan1in2out'
        obj.target       = 'pan1in2out'
        obj.uselib_local = 'libardour libardour_cp libpbd'
        obj.vnum         = LIBARDOUR_PAN1IN2OUT_LIB_VERSION
        obj.install_path = os.path.join(bld.env['LIBDIR'], 'ardour3', 'panners')

def shutdown():
        autowaf.shutdown()

