#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBARDOUR_PAN1IN2OUT_LIB_VERSION = '1.0.0'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = [ 'panner_1in2out.cc' ]
    obj.export_includes = ['.']
    obj.defines     = [ 'PACKAGE="libardour_pan1in2out"' ]
    if bld.is_defined ('INTERNAL_SHARED_LIBS'):
        obj.defines += [ 'LIBARDOUR_DLL=1', 'LIBPBD_DLL=1', 'LIBEVORAL_DLL=1' ]
    obj.includes     = ['.']
    obj.name         = 'libardour_pan1in2out'
    obj.target       = 'pan1in2out'
    obj.use          = 'libardour libardour_cp libpbd'
    obj.vnum         = LIBARDOUR_PAN1IN2OUT_LIB_VERSION
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'ardour3', 'panners')

def shutdown():
    autowaf.shutdown()
