#!/usr/bin/env python
import autowaf
import os

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBSURFACES_LIB_VERSION = '4.1.0'

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
	autowaf.set_options(opt)

def configure(conf):
	autowaf.configure(conf)

def build(bld):
	obj = bld.new_task_gen('cxx', 'shlib')
	obj.source = '''
		interface.cc
		powermate.cc
	'''
	obj.export_incdirs = ['./powermate']
	obj.cxxflags     = '-DPACKAGE="ardour_powermate"'
	obj.includes     = ['.', './powermate']
	obj.name         = 'libpowermate'
	obj.target       = 'powermate'
	obj.uselib_local = 'libardour libsurfaces'
	obj.vnum         = LIBSURFACES_LIB_VERSION
	obj.install_path = os.path.join(bld.env['LIBDIR'], 'ardour3')

def shutdown():
	autowaf.shutdown()

