#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBARDOUR_POWERMATE_LIB_VERSION = '4.1.0'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            interface.cc
            powermate.cc
    '''
    obj.export_includes = ['.']
    obj.cxxflags     = '-DPACKAGE="ardour_powermate"'
    obj.includes     = ['.' ]
    obj.name         = 'libpowermate'
    obj.target       = 'powermate'
    obj.use          = 'libardour libardour_cp'
    obj.vnum         = LIBARDOUR_POWERMATE_LIB_VERSION
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'ardour3', 'surfaces')

def shutdown():
    autowaf.shutdown()
