# -*- python -*-

import os
import os.path
import glob

cairomm_files = glob.glob('cairomm/*.cc')

Import('env libraries install_prefix')
cairomm = env.Copy()
cairomm.Merge([libraries['cairo']])

libcairomm = cairomm.SharedLibrary('cairomm', cairomm_files)
Default(libcairomm)

env.Alias('install', env.Install(os.path.join(install_prefix, env['LIBDIR'], 'ardour2'), libcairomm))

env.Alias('tarball', env.Distribute (env['DISTTREE'],
                                     [ 'SConscript'] + 
				     cairomm_files + 
				     glob.glob('cairomm/*.h') 
				     ))
