#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os
import sys
import re

I18N_PACKAGE = 'coreaudio-backend'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = [ 'coreaudio_backend.cc',
                   'coreaudio_pcmio.cc',
                   'coremidi_io.cc'
                 ]
    obj.includes = ['.']
    obj.name     = 'coreaudio_backend'
    obj.target   = 'coreaudio_backend'
    obj.use      = 'libardour libpbd'
    obj.framework = [ 'CoreAudio', 'AudioToolbox', 'CoreServices', 'CoreMidi' ]
    obj.install_path  = os.path.join(bld.env['LIBDIR'], 'backends')
    obj.defines = ['PACKAGE="' + I18N_PACKAGE + '"',
                   'ARDOURBACKEND_DLL_EXPORTS', 'COREAUDIO_108'
                  ]

    # OSX 10.6 or later
    obj.defines += ['COREAUDIO_108']
