#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Version of this package (even if built as a child)
LIBSURFACES_VERSION = '4.1.0'

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBSURFACES_LIB_VERSION = '4.1.0'

# Variables for 'waf dist'
APPNAME = 'libsurfaces'
VERSION = LIBSURFACES_VERSION

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    # Generic MIDI
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            generic_midi_control_protocol.cc
            interface.cc
            midicontrollable.cc
    '''
    obj.export_includes = ['./generic_midi']
    obj.defines     = [ 'PACKAGE="ardour_frontier"' ]
    if bld.is_defined ('INTERNAL_SHARED_LIBS'):
        obj.defines += [ 'LIBARDOUR_DLL=1', 'LIBCONTROLCP_DLL=1', 'LIBPBD_DLL=1' ]
    obj.includes     = ['.', './generic_midi']
    obj.name         = 'libgeneric_midi'
    obj.target       = 'generic_midi'
    obj.use          = 'libardour libardourcp'
    obj.vnum         = LIBSURFACES_LIB_VERSION
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'ardour3', 'surfaces')

def shutdown():
    autowaf.shutdown()
