#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    pass

def build(bld):
    # Generic MIDI
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            generic_midi_control_protocol.cc
            interface.cc
            midicontrollable.cc
    '''
    obj.export_includes = ['./generic_midi']
    obj.defines      = [ 'PACKAGE="ardour_frontier"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = ['.', './generic_midi']
    obj.name         = 'libgeneric_midi'
    obj.target       = 'generic_midi'
    obj.uselib       = 'XML OSX'
    obj.use          = 'libardour libardourcp'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')

def shutdown():
    autowaf.shutdown()
