# -*- python -*-

import os
import os.path
import glob

Import('env')
sanitycheck = env.Clone()

if sanitycheck['IS_OSX'] != 0:
    print ("Skip sanity check - code is Linux-only")
else:
    print ("OSX env = ", env['IS_OSX'])
    #sc = sanitycheck.Program('sanityCheck', ['main.cpp', 'systemtest.cpp'])
    #Default(sc)

