#!/usr/bin/env python
from waflib.extras import autowaf as autowaf

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxprogram')
    obj.includes = [ '.' ]
    obj.source = [ 'main.cpp', 'systemtest.cpp' ]
    obj.target = 'sanityCheck'
    obj.name = 'sanityCheck'
    obj.install_path = bld.env['LIBDIR']
