#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = [ 'vbap_speakers.cc', 'vbap.cc'  ]
    obj.export_includes = ['.']
    obj.defines      = ['PACKAGE="libardour_panvbap"']
    obj.defines     += ['ARDOURPANNER_DLL_EXPORTS']
    obj.includes     = ['.']
    obj.name         = 'libardour_panvbap'
    obj.target       = 'panvbap'
    obj.use          = 'libardour libardour_cp libpbd'
    obj.uselib       = 'GLIBMM XML OSX'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'panners')

def shutdown():
    autowaf.shutdown()
