#!/usr/bin/env python
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = [ 'vbap_speakers.cc', 'vbap.cc'  ]
    obj.defines      = ['PACKAGE="libardour_panvbap"']
    obj.defines     += ['ARDOURPANNER_DLL_EXPORTS']
    obj.includes     = ['.']
    obj.name         = 'libardour_panvbap'
    obj.target       = 'panvbap'
    obj.use          = 'libardour libardour_cp libpbd'
    obj.uselib       = 'GLIBMM XML OSX'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'panners')
