#!/usr/bin/env python

import os

def configure(conf):
    pass

def build(bld):
    maps = bld.path.ant_glob ('plugin*')
    bld.install_files (os.path.join(bld.env['DATADIR'], 'plugin_metadata'),
                       maps)

def options(opt):
    pass
