#!/usr/bin/env python
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            komplete_kontrol_a.cc
            kka_protocol.cc
            interface.cc
    '''
    obj.defines      = [ 'PACKAGE="ardour_komplete_kontrol_a"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = [ '.' ]
    obj.name         = 'libardour_komplete_kontrol_a'
    obj.target       = 'ardour_komplete_kontrol_a'
    obj.uselib       = 'XML OSX GLIBMM GIOMM'
    obj.use          = 'libardour libardour_cp libpbd hidapi'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')
