# -*- python -*-

import os
import os.path
import glob

appleutility_files = glob.glob('*.cpp') 

Import('env install_prefix')
appleutility = env.Copy()

appleutility.Append(LINKFLAGS='-framework AudioToolbox')
appleutility.Append(LINKFLAGS='-framework AudioUnit')
appleutility.Append(LINKFLAGS='-framework CoreFoundation')
appleutility.Append(LINKFLAGS='-framework CoreServices')

libappleutility = appleutility.SharedLibrary('appleutility', appleutility_files)
if appleutility['COREAUDIO']:
    Default(libappleutility)
    env.Alias('install', env.Install(os.path.join(install_prefix, 'lib/ardour2'), libappleutility))

env.Alias('tarball', env.Distribute (env['DISTTREE'], ['SConscript'] + appleutility_files + glob.glob('*.h') ))
