#!/usr/bin/env python
import autowaf
import os

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBARDOUR_CP_LIB_VERSION = '4.1.0'

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
	autowaf.set_options(opt)

def configure(conf):
	autowaf.configure(conf)

def build(bld):
	obj = bld.new_task_gen('cxx', 'shlib')
	obj.source = '''
		basic_ui.cc
		control_protocol.cc
		smpte.cc
	'''
	obj.export_incdirs = ['.', './control_protocol' ]
	obj.cxxflags     = '-DPACKAGE="ardour_cp"'
	obj.includes     = ['.', './control_protocol']
	obj.name         = 'libardour_cp'
	obj.target       = 'ardourcp'
	obj.uselib_local = 'libardour'
	obj.vnum         = LIBARDOUR_CP_LIB_VERSION
	obj.install_path = os.path.join(bld.env['LIBDIR'], 'ardour3')

def shutdown():
	autowaf.shutdown()

