#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
APPNAME = 'libardour_cp'
LIBARDOUR_CP_LIB_VERSION = '4.1.0'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            basic_ui.cc
            control_protocol.cc
    '''
    obj.export_includes = ['.', './control_protocol' ]
    obj.cxxflags     = '-DPACKAGE="ardour_cp" -fPIC'
    obj.includes     = ['.', './control_protocol']
    obj.name         = 'libardour_cp'
    obj.target       = 'ardourcp'
    obj.use          = 'libardour libtimecode'
    obj.vnum         = LIBARDOUR_CP_LIB_VERSION
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'ardour3')

def shutdown():
    autowaf.shutdown()
