# -*- python -*-
Import('env libraries')

cassowary = env.Copy(YACCFLAGS="-d")

domain = 'libcassowary'
cassowary.Append(DOMAIN=domain,MAJOR=0,MINOR=60,MICRO=3)

cassowary_files = Split("""
ClAbstractVariable.cc
ClConstraint.cc
ClLinearExpression.cc
ClSolver.cc 
ClSimplexSolver.cc
ClStrength.cc
ClSymbolicWeight.cc
ClTableau.cc
ClVariable.cc
ClFloatVariable.cc
ClSlackVariable.cc
ClDummyVariable.cc
ClReader.cc
ClReader-lex.cc
""")

cassowary.Append(CCFLAGS="-D_REENTRANT")

cassowary.CXXFile(target = ['ClReader.cc', 'ClReader.cc.h'], source = 'ClReader.yy')
cassowary.CXXFile(target = 'ClReader-lex.cc', source = 'ClReader.ll')

libcassowary = cassowary.StaticLibrary('cassowary', cassowary_files)
Default(libcassowary)
