#!/bin/sh
#
# Author: Aaron Voisine <aaron@voisine.org>

CWD="`dirname \"$0\"`"
TMP=/tmp/$UID/TemporaryItems

ps -wx -ocommand | grep -e '[X]11' > /dev/null
if [ "$?" != "0" -a ! -f ~/.xinitrc ]; then
    echo "rm -f ~/.xinitrc" > ~/.xinitrc
    sed 's/xterm/# xterm/' /usr/X11R6/lib/X11/xinit/xinitrc >> ~/.xinitrc
fi

mkdir -p $TMP
cp -f "$CWD/bin/getdisplay.sh" $TMP
rm -f $TMP/display
open-x11 $TMP/getdisplay.sh || \
open -a XDarwin $TMP/getdisplay.sh || \
echo ":0" > $TMP/display

while [ "$?" == "0" -a ! -f $TMP/display ]; do sleep 1; done
export "DISPLAY=`cat $TMP/display`"

ps -wx -ocommand | grep -e '[X]11' > /dev/null || exit 11

cd ~/
exec "$CWD/bin/exporter" "$@"
