#!/bin/sh

#
# NOTE: Leopard appears not to set PATH for this script, so be absolutely certain
# never to use any other program without fully specifying the path.
#
# this is used to detect a missing JACK install which
# is the most common thing causing startup crashes.
# 

if test ! -x /usr/local/bin/jackd -a ! -x /usr/bin/jackd ; then
   /usr/bin/osascript -e 'tell application "Finder"
display dialog "You do not have JACK installed. Ardour will not run without it. See http://jackaudio.org/ for info" buttons["OK"]
end tell'
   exit 1
fi

# this needs to be set so that we can restore the environment when we want to find JACK (or similar)
export PREBUNDLE_ENV="$(env)"

# all clear, lets go
# this quoting is all needed to handle installation
# in folders likes /home/user/Frank's Wild Years

CWD="`/usr/bin/dirname \"$0\"`"
exec "$CWD/Ardour3.bin" "$*"
