#!/bin/sh

#
# NOTE: Leopard appears not to set PATH for this script, so be absolutely certain
# never to use any other program without fully specifying the path.
#

# this needs to be set so that we can restore the environment when we want to find JACK (or similar)
export PREBUNDLE_ENV="$(env)"

# all clear, lets go
# this quoting is all needed to handle installation
# in folders likes /home/user/Frank's Wild Years

CWD="`/usr/bin/dirname \"$0\"`"
exec "$CWD/Tracks.bin" "$@"
