#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import Options
import os
import sys
import re

I18N_PACKAGE = 'portaudio-backend'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)
    autowaf.check_pkg(conf, 'portaudio-2.0', uselib_store='PORTAUDIO', atleast_version='19')

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = [ 'portaudio_backend.cc',
                   'portaudio_io.cc',
#                  'portmidi_io.cc'
                 ]
    obj.includes = ['.']
    obj.name     = 'portaudio_backend'
    obj.target   = 'portaudio_backend'
    obj.use      = 'libardour libpbd'
    obj.uselib   = ['PORTAUDIO']
    obj.install_path  = os.path.join(bld.env['LIBDIR'], 'backends')
    obj.defines = ['PACKAGE="' + I18N_PACKAGE + '"',
                   'ARDOURBACKEND_DLL_EXPORTS'
                  ]
