# -*- python -*-

import os
import os.path
import glob

sigc2_files = glob.glob('sigc++/*.cc') + glob.glob('sigc++/functors/*.cc') + glob.glob('sigc++/adaptors/lambda/*.cc')

Import('env install_prefix')
sigc2 = env.Copy()

libsigc2 = sigc2.SharedLibrary('sigc++2', sigc2_files)

if os.path.exists ('CVS') or os.path.exists ('.svn'):
    sigc2_configure_script = sigc2.Command ('configure', 'configure.ac', 'cd libs/sigc++2 && ./autogen.sh && cd -', ENV=os.environ)
    sigc2_config_h = sigc2.Command('sigc++config.h', [sigc2_configure_script, 'sigc++config.h.in'], 'cd libs/sigc++2 && ./configure && cd -', ENV=os.environ)
    Default([sigc2_config_h,libsigc2])
else:
    Default([libsigc2])

env.Alias('install', env.Install(os.path.join(install_prefix, 'lib/ardour2'), libsigc2))

env.Alias('tarball', env.Distribute (env['DISTTREE'],
                                     [ 'NEWS', 'README', 'AUTHORS', 'ChangeLog',
                                       'configure', 'Makefile.am', 'SConscript',
                                       'sigc++/Makefile.am', 
                                       'sigc++config.h',
                                       ] + sigc2_files +
                                     glob.glob('sigc++/*.h') +
                                     glob.glob('sigc++/functors/*.h') + glob.glob('sigc++/adaptors/lambda/*.h') +
                                     glob.glob('sigc++/adaptors/*.h')
                                     ))
