# -*- python -*-

import glob
import os

sigc2_files = glob.glob('sigc++/*.cc') + glob.glob('sigc++/functors/*.cc') + glob.glob('sigc++/adaptors/lambda/*.cc')

Import('env')
sigc2 = env.Copy()

if os.path.exists ('CVS'):
    sigc2_configure_script = sigc2.Command ('configure', 'configure.ac', 'cd libs/sigc++2; ./autogen.sh; cd -', ENV=os.environ)
    sigc2_config_h = sigc2.Command('sigc++config.h', [sigc2_configure_script, 'sigc++config.h.in'], 'cd libs/sigc++2; ./configure; cd -', ENV=os.environ)
    Default([sigc_config_h,libsigc])
else:
    Default([libsigc])

libsigc2 = sigc2.StaticLibrary('sigc++2', sigc2_files)
Default([sigc2_config_h, libsigc2])
