#!/usr/bin/env python

controlcp_sources = [
    'basic_ui.cc',
    'control_protocol.cc',
    ]

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    if bld.is_defined ('INTERNAL_SHARED_LIBS'):
        obj              = bld.shlib(features = 'c cxx cshlib cxxshlib', source=controlcp_sources)
        # defines for this library
        obj.defines      = [ 'LIBCONTROLCP_DLL_EXPORTS' ]
    else:
        obj              = bld.stlib(features = 'c cxx cstlib cxxstlib', source=controlcp_sources)
        obj.cxxflags     = [ bld.env['compiler_flags_dict']['pic'] ]
        obj.defines      = [ ]

    obj.export_includes = ['.']
    obj.defines    +=  [ 'PACKAGE="ardour_cp"' ]
    obj.includes     = ['.', './control_protocol']
    obj.name         = 'libardour_cp'
    obj.target       = 'ardourcp'
    obj.use          = 'libardour libpbd'
    obj.uselib       = 'GLIBMM SIGCPP XML OSX'
    obj.install_path = bld.env['LIBDIR']
