#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import Options, TaskGen
import waflib.Logs as Logs, waflib.Utils as Utils
import shutil
import sys
import time

top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    conf.load('misc')
    conf.load('compiler_cxx')
    autowaf.configure(conf)

def build(bld):
    obj = bld (features = 'cxx c cxxprogram')
    obj.source    = 'cfgtool.cc'
    obj.target    = 'cfgtool'
    obj.use       = [ 'libpbd', 'libardour', ]
