#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Mandatory variables
top = '.'
out = 'build'


def options(opt):
    autowaf.set_options(opt)


def configure(conf):
    pass


def build(bld):
    obj = bld(features='cxx cxxshlib')
    obj.source = '''
        launch_control_xl.cc
        controllers.cc
        interface.cc
        midi_byte_array.cc
        leds.cc
        gui.cc
    '''
    obj.export_includes = ['.']
    obj.defines = ['PACKAGE="ardour_launch_control_xl"']
    obj.defines += ['ARDOURSURFACE_DLL_EXPORTS']
    obj.defines += ['VERSIONSTRING="' + bld.env['VERSION'] + '"']
    obj.includes = ['.', './launch_control_xl']
    obj.name = 'libardour_launch_control_xl'
    obj.target = 'ardour_launch_control_xl'
    obj.uselib = 'GTKMM SIGCPP XML OSX'
    obj.use = 'libardour libardour_cp libpbd libevoral libcanvas libtemporal'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')


def shutdown():
    autowaf.shutdown()
