import os.path

Import ('env install_prefix')

clearlooks = env.Copy()

clearlooks.Replace(CCFLAGS = ' `pkg-config --cflags gtk+-2.0` ',
                   LINKFLAGS = ' `pkg-config --libs gtk+-2.0` ')

libclearlooks = clearlooks.SharedLibrary('clearlooks', [
    'clearlooks_draw.c',
    'clearlooks_rc_style.c',
    'clearlooks_style.c',
    'clearlooks_theme_main.c',
    'support.c'
])

usable_libclearlooks = clearlooks.Install ('engines', libclearlooks)
Default (usable_libclearlooks)

env.Alias('install',
          env.Install(os.path.join(install_prefix,'lib/ardour2/engines'),
                      libclearlooks))
