#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            shuttlepro.cc
            shuttlepro_gui.cc
            interface.cc
    '''
    obj.export_includes = ['./shuttlepro']
    obj.defines      = [ 'PACKAGE="ardour_shuttlepro"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = ['.', '../libs']
    obj.name         = 'libardour_shuttlepro'
    obj.target       = 'ardour_shuttlepro'
    obj.uselib       = 'GTKMM USB'
    obj.use          = 'libardour libardour_cp libgtkmm2ext'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')

def shutdown():
    autowaf.shutdown()
