#!/usr/bin/env python
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    if bld.is_defined('AUDIOUNIT_SUPPORT'):
        obj = bld (features = 'cxx c cxxprogram')
        obj.source    = 'au-scanner.cc'
        obj.target    = 'ardour-au-scanner'
        obj.includes  = [ '../pbd/', '../ardour/', '..' ]
        obj.defines   = [
            'AU_SCANNER_APP',
            'VERSIONSTRING="' + bld.env['VERSION'] + '"',
            'PACKAGE="' + bld.env['INTERNAL_NAME'] + '"',
            'LIBARDOUR="' + bld.env['INTERNAL_NAME'] + '"',
            'LOCALEDIR="' + os.path.join(os.path.normpath(bld.env['DATADIR']), 'locale') + '"',
            ]
        obj.use = [ 'libpbd', 'libappleutility', 'libtemporal', 'libevoral' ]
        obj.uselib = 'GIOMM DL UUID ARCHIVE CURL XML COREAUDIO AUDIOUNITS OSX'
        obj.install_path = os.path.join(bld.env['LIBDIR'])
        obj.cxxflags = ['-Wno-deprecated-declarations']
