#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import TaskGen
import os
import sys

# Mandatory variables
top = '.'
out = 'build'

# needed for code used from libardour
I18N_PACKAGE = 'ardour'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    pass

def build(bld):
    if bld.is_defined('AUDIOUNIT_SUPPORT'):
        obj = bld (features = 'cxx c cxxprogram')
        obj.source    = 'au-scanner.cc'
        obj.target    = 'ardour-au-scanner'
        obj.includes  = [ '../pbd/', '../ardour/', '..' ]
        obj.defines   = [
            'AU_SCANNER_APP',
            'VERSIONSTRING="' + str(bld.env['VERSION']) + '"',
            'PACKAGE="' + I18N_PACKAGE + str(bld.env['MAJOR']) + '"',
            'LIBARDOUR="' + bld.env['lwrcase_dirname'] + '"',
            'LOCALEDIR="' + os.path.join(os.path.normpath(bld.env['DATADIR']), 'locale') + '"',
            ]
        obj.use = [ 'libpbd', 'libappleutility', 'libtemporal', 'libevoral' ]
        obj.uselib = 'GIOMM DL UUID ARCHIVE CURL XML COREAUDIO AUDIOUNITS OSX'
        obj.install_path = os.path.join(bld.env['LIBDIR'])
        obj.cxxflags = ['-Wno-deprecated-declarations']
