#!/bin/sh
#
# Copyright (C) Paul Davis 2011-2012

while true ; do 
   if [ -x ./waf ] ; then
      ./waf "$@"
      if [ "$?" -ne "0" ]; then
	exit 1
      else
	exit 0
      fi
   fi
   cd ..
   if [ `pwd` = '/' ] ; then break; fi
done

