#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = [
            'faderport8.cc',
            'faderport8_interface.cc',
            'fp8_controls.cc',
            'fp8_strip.cc',
            'callbacks.cc',
            'actions.cc',
            'gui.cc'
    ]
    obj.export_includes = ['.']
    obj.defines      = [ 'PACKAGE="ardour_faderport8"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = [ '.', './faderport8']
    obj.name         = 'libardour_faderport8'
    obj.target       = 'ardour_faderport8'
    obj.uselib       = 'GTKMM GTK GDK XML'
    obj.use          = 'libardour libardour_cp libgtkmm2ext libpbd'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')

def shutdown():
    autowaf.shutdown()
