# -*- python -*-

import os
import os.path
import glob

plugin_files = Split("""
plugins.cpp
AmplitudeFollower.cpp
PercussionOnsetDetector.cpp
SpectralCentroid.cpp
ZeroCrossing.cpp
Onset.cpp
""")

Import('env install_prefix libraries')
vampplugs = env.Clone()

vampplugs.Append (CPPATH='#libs/vamp-sdk/vamp', CXXFLAGS="-Ilibs/vamp-sdk")
vampplugs.Merge ([libraries['vamp'],
                  libraries['vamphost'],
                  libraries['aubio'],
                  libraries['fftw3f']
                  ])

sources = plugin_files

libvampplugins = vampplugs.SharedLibrary('ardourvampplugins', sources)

Default(libvampplugins)

env.Alias('install', env.Install(os.path.join(install_prefix, env['LIBDIR'], 'ardour2', 'vamp'), libvampplugins))

env.Alias('tarball', env.Distribute (env['DISTTREE'],
                                     [ 'SConscript' ] +
                                     plugin_files +
                                     glob.glob('*.h')))
