# -*- python -*-

import os
import os.path
import glob

plugin_files = glob.glob ("*.cpp")

Import('env install_prefix libraries')
vampplugs = env.Copy()

vampplugs.Append (CPPATH='#libs/vamp-sdk/vamp', CXXFLAGS="-Ilibs/vamp-sdk")
vampplugs.Merge ([libraries['vamp'],
                  libraries['vamphost']
                  ])

libvampplugins = vampplugs.SharedLibrary('ardourvampplugins', plugin_files)

Default(libvampplugins)

env.Alias('install', env.Install(os.path.join(install_prefix, env['LIBDIR'], 'ardour3', 'vamp'), libvampplugins))

env.Alias('tarball', env.Distribute (env['DISTTREE'],
                                     [ 'SConscript' ] +
                                     plugin_files +
                                     glob.glob('*.h')))
