import glob

gtkmm2_files = glob.glob('gtkmm/*.cc')

Import('env libraries')
gtkmm2 = env.Copy()
gtkmm2.Merge([libraries['glibmm2'], libraries['gtk2'], libraries['sigc2'], libraries['pangomm'], libraries['atkmm'], libraries['gdkmm2'] ])

libgtkmm2 = gtkmm2.StaticLibrary('gtkmm2', gtkmm2_files)
Default(libgtkmm2)
