#!/usr/bin/python

import os

top = '.'
out = 'build'

def configure(conf):
    pass

def build(bld):
    devinfo = bld.path.ant_glob ('*.device')
    profiles = bld.path.ant_glob ('*.profile')
    bld.install_files (os.path.join(bld.env['DATADIR'], 'ardour3', 'mcp'), devinfo)
    bld.install_files (os.path.join(bld.env['DATADIR'], 'ardour3', 'mcp'), profiles)

def options(opt):
    pass
