#!/usr/bin/env python
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            contourdesign.cc
            contourdesign_gui.cc
            jump_distance_widget.cc
            button_config_widget.cc
            interface.cc
    '''
    obj.defines      = [ 'PACKAGE="ardour_contourdesign"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = ['.', '../libs', '../../widgets']
    obj.name         = 'libardour_contourdesign'
    obj.target       = 'ardour_contourdesign'
    obj.uselib       = 'USB XML OSX PANGOMM'
    obj.use          = 'libardour libardour_cp libgtkmm2ext libpbd libwidgets'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')
    if bld.is_defined('YTK'):
        obj.use    += ' libytkmm'
        obj.uselib += ' GLIBMM GIOMM'
    else:
        obj.uselib += ' GTKMM'
