#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            contourdesign.cc
            contourdesign_gui.cc
            jump_distance_widget.cc
            button_config_widget.cc
            interface.cc
    '''
    obj.export_includes = ['./contourdesign']
    obj.defines      = [ 'PACKAGE="ardour_contourdesign"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = ['.', '../libs', '../../widgets']
    obj.name         = 'libardour_contourdesign'
    obj.target       = 'ardour_contourdesign'
    obj.uselib       = 'GTKMM USB XML OSX'
    obj.use          = 'libardour libardour_cp libgtkmm2ext libpbd libwidgets'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')

def shutdown():
    autowaf.shutdown()
