#!/bin/sh

BASE=$1

if [ x$BASE = "x" ] ; then 
   exit 1
fi

if mount | grep --silent vmshare ; then
    :
else
    sudo mount -t vboxsf vmshare $HOME/vmshare
fi

cd $BASE || exit 1
svn update || exit 1
./waf configure --strict --noconfirm || exit 1
./waf || exit 1
cd tools/linux_packaging || exit 1
./build --public --nostrip || exit 1
file=`ls -t *.bz2 | head -1`
echo "Copying $file to shared folder ..."
cp $file $HOME/vmshare || exit 1

exit 0
