#!/bin/sh

vbm=VBoxManage
basedir=/home/harrison/ardour/3.0/tools/linux_packaging
tooldir=$basedir/tools/linux_packaging
u=harrison
p=harrison

for VM in Build_64bit_804s ; do
    $vbm startvm $VM --type headless
    echo "Waiting for guest control to be available (12 seconds) ... "
    sleep 12
    echo "Running $tooldir/noderun $basedir on $VM ... "
    $vbm guestcontrol exec $VM /bin/sh --arguments $tooldir/noderun --arguments $basedir --username $u --password $p --wait-for stdout
    status=$?
    $vbm controlvm $VM savestate
done
