#!/usr/bin/env python
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            wiimote.cc
            interface.cc
    '''
    obj.defines      = [ 'PACKAGE="ardour_wiimote"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = ['.', '../libs']
    obj.name         = 'libardour_wiimote'
    obj.target       = 'ardour_wiimote'
    obj.uselib       = 'CWIID XML'
    obj.use          = 'libardour libardour_cp libgtkmm2ext'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')
    if bld.is_defined('YTK'):
        obj.use    += 'libytkmm'
        obj.uselib += ' GLIBMM GIOMM PANGOMM'
    else:
        obj.uselib += ' GTKMM'
