#!/usr/bin/env python
import autowaf

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBSURFACES_LIB_VERSION = '4.1.0'

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
	autowaf.set_options(opt)

def configure(conf):
	autowaf.configure(conf)

def build(bld):
	obj = bld.new_task_gen('cxx', 'shlib')
	obj.source = '''
		wiimote.cc
		interface.cc
	'''
	obj.export_incdirs = ['./wiimote']
	obj.cxxflags     = '-DPACKAGE=\\\"ardour_wiimote\\\"'
	obj.includes     = ['.', './wiimote']
	obj.name         = 'libwiimote'
	obj.target       = 'wiimote'
	obj.uselib_local = 'libardour libsurfaces'
	obj.vnum         = LIBSURFACES_LIB_VERSION
	obj.install_path = ''
	
def shutdown():
	autowaf.shutdown()

