#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBARDOUR_MCP_LIB_VERSION = '4.1.0'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            button.cc
            controls.cc
            device_info.cc
            fader.cc
            gui.cc
            interface.cc
            jog.cc
            led.cc
            mackie_control_protocol.cc
            mackie_jog_wheel.cc
            mcp_buttons.cc
            meter.cc
            midi_byte_array.cc
            pot.cc
            strip.cc
            surface.cc
            surface_port.cc
            types.cc
    '''
    obj.export_includes = ['./mackie']
    obj.cxxflags     = '-DPACKAGE="ardour_mackie"'
    # need ../libs because some GTK2 header files require stuff there
    obj.includes     = ['.', '../libs']
    obj.name         = 'libardour_mcp'
    obj.target       = 'ardour_mcp'
    obj.uselib       = 'GTKMM'
    obj.use          = 'libardour libardour_cp libgtkmm2ext'
    obj.vnum         = LIBARDOUR_MCP_LIB_VERSION
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'ardour3', 'surfaces')

def shutdown():
    autowaf.shutdown()
