#!/usr/bin/python

import os

top = '.'
out = 'build'

def configure(conf):
    pass

def build(bld):

    subst_dict = {}
    subst_dict['ARDOUR_VERSION'] = bld.env['VERSION']

    obj = bld(features = 'subst')
    obj.name = 'manual'
    obj.source = [ 'xml/entities.ent.in' ]
    obj.target = [ 'ent/entities.ent' ]
    obj.dict = subst_dict

def options(opt):
    pass
