#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBARDOUR_TRANZPORT_LIB_VERSION = '4.1.0'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            button_events.cc
            buttons.cc
            general.cc
            init.cc
            interface.cc
            io.cc
            io_usb.cc
            lcd.cc
            lights.cc
            mode.cc
            panner.cc
            screen.cc
            show.cc
            state.cc
            wheel.cc
            wheel_modes.cc
    '''
    obj.export_includes = ['./tranzport']
    obj.defines     = [ 'PACKAGE="ardour_tranzport"' ]
    obj.includes     = ['.', './tranzport']
    obj.name         = 'libardour_tranzport'
    obj.defines      = [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.target       = 'ardour_tranzport'
    obj.use          = 'libardour libardour_cp'
    obj.vnum         = LIBARDOUR_TRANZPORT_LIB_VERSION
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'ardour3', 'surfaces')

def shutdown():
    autowaf.shutdown()
