#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            button_events.cc
            buttons.cc
            general.cc
            init.cc
            interface.cc
            io.cc
            io_usb.cc
            lcd.cc
            lights.cc
            mode.cc
            panner.cc
            screen.cc
            show.cc
            state.cc
            wheel.cc
            wheel_modes.cc
    '''
    obj.export_includes = ['./tranzport']
    obj.defines      = [ 'PACKAGE="ardour_tranzport"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = ['.', './tranzport']
    obj.name         = 'libardour_tranzport'
    obj.target       = 'ardour_tranzport'
    obj.uselib       = 'XML OSX'
    obj.use          = 'libardour libardour_cp'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')

def shutdown():
    autowaf.shutdown()
