#ifndef _LIBGNOMEUIMM_CONFIG_H
#define _LIBGNOMEUIMM_CONFIG_H 1

#include <gtkmmconfig.h>

/* version numbers */
#define LIBGNOMEUIMM_MAJOR_VERSION 2
#define LIBGNOMEUIMM_MINOR_VERSION 16
#define LIBGNOMEUIMM_MICRO_VERSION 0

#endif /* _LIBGNOMEUIMM_CONFIG_H */
