#!/usr/bin/env python
import re
import sys

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'c cprogram')
    obj.source = [ 'abicheck.c' ]
    obj.target = 'gcc-glibmm-abi-check'
    obj.name = 'gcc-glibmm-abi-check'
    if re.search ("bsd", sys.platform) is None:
        obj.lib = 'dl'
    obj.install_path = None
