#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import Options
import os
import re
import sys

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'c cprogram')
    obj.source = [ 'abicheck.c' ]
    obj.target = 'gcc-glibmm-abi-check'
    obj.name = 'gcc-glibmm-abi-check'
    if re.search ("bsd", sys.platform) == None:
        obj.lib = 'dl'
    obj.install_path = None
