# -*- python -*-

import os
import glob
template_files = glob.glob('*.template.in')
files = glob.glob('*.template')

Import('env install_prefix subst_dict')

template_build = []

for template in template_files:
    template_build = template_build + [env.SubstInFile (template[:-3], template, SUBST_DICT = subst_dict)]

Default(template_build)

env.Alias('install', env.Install(os.path.join(install_prefix, 'share', 'ardour3', 'templates'), files))
env.Alias('tarball', env.Distribute (env['DISTTREE'], [ 'SConscript' ] + template_build))
