#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBARDOUR_GENERIC_MIDI_LIB_VERSION = '4.1.0'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            generic_midi_control_protocol.cc
            gmcp_gui.cc
            interface.cc
            midiinvokable.cc
            midicontrollable.cc
            midifunction.cc
            midiaction.cc
    '''
    obj.export_includes = ['.']
    obj.defines     = [ 'PACKAGE="ardour_genericmidi"' ]
    if bld.is_defined ('INTERNAL_SHARED_LIBS'):
        obj.defines += [ 'LIBARDOUR_DLL=1', 'LIBCONTROLCP_DLL=1', 'LIBPBD_DLL=1', 'LIBGTKMM2EXT_DLL=1', 'LIBEVORAL_DLL=1' ]
    obj.includes     = ['.', './generic_midi']
    obj.name         = 'libardour_generic_midi'
    obj.target       = 'ardour_generic_midi'
    obj.defines      = [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.uselib       = 'GTKMM GTK GDK'
    obj.use          = 'libardour libardour_cp libgtkmm2ext libpbd'
    obj.vnum         = LIBARDOUR_GENERIC_MIDI_LIB_VERSION
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'ardour3', 'surfaces')
    obj.defines      += [
        'PROGRAM_NAME="' + bld.env['PROGRAM_NAME'] + '"'
        ]

def shutdown():
    autowaf.shutdown()
