#!/usr/bin/env python
import os
import sys

cocoatea_sources = [
    'cocoatea.mm',
    'view.mm',
    'meter.mm'
]

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    # just the normal executable version of the GTK GUI
    obj = bld (features = 'cxx c cxxprogram')
    # this program does not do the whole hidden symbols thing
    obj.cxxflags = [ '-fvisibility=default' ]
    obj.source    = cocoatea_sources
    obj.target = 'cocoatea' 
    obj.includes = ['.']
    obj.use      = []

    obj.defines = [
        'DATA_DIR="' + os.path.normpath(bld.env['DATADIR']) + '"',
        'CONFIG_DIR="' + os.path.normpath(bld.env['SYSCONFDIR']) + '"',
        ]
    obj.install_path = bld.env['LIBDIR']
    obj.uselib       = 'OSX'

