#!/usr/bin/env python
import autowaf
import os

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBARDOUR_OSC_LIB_VERSION = '4.1.0'

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
	autowaf.set_options(opt)

def configure(conf):
	autowaf.configure(conf)
	autowaf.check_pkg(conf, 'liblo', uselib_store='LO')

def build(bld):
	obj = bld.new_task_gen('cxx', 'shlib')
	obj.source = '''
		osc.cc
		osc_controllable.cc
		interface.cc
	'''
	obj.export_incdirs = ['.']
	obj.cxxflags     = '-DPACKAGE="ardour_cp"'
	obj.includes     = ['.', './osc']
	obj.name         = 'libardour_osc'
	obj.target       = 'osc'
	obj.uselib       = ' LO '
	obj.uselib_local = 'libardour libardour_cp'
	obj.vnum         = LIBARDOUR_OSC_LIB_VERSION
	obj.install_path = os.path.join(bld.env['LIBDIR'], 'ardour3')

def shutdown():
	autowaf.shutdown()

