#!/usr/bin/env python
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            osc.cc
            osc_controllable.cc
            osc_route_observer.cc
            osc_select_observer.cc
            osc_global_observer.cc
            osc_cue_observer.cc
            interface.cc
            osc_gui.cc
    '''
    obj.defines      = [ 'PACKAGE="ardour_osc"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = ['.', './osc']
    obj.name         = 'libardour_osc'
    obj.target       = 'ardour_osc'
    obj.uselib       = 'LO XML OSX'
    obj.use          = 'libardour libardour_cp libgtkmm2ext libpbd'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')
    if bld.is_defined('YTK'):
        obj.use    += ' libytkmm'
        obj.uselib += ' GLIBMM GIOMM PANGOMM'
    else:
        obj.uselib += ' GTKMM'
