import glob
import os

glibmm2_files = glob.glob('glibmm/*.cc')

Import('env libraries')

glibmm2 = env.Copy()
glibmm2.Merge([libraries['sigc2'], libraries['glib2']])

glibmm2.Append(CXXFLAGS='-DHAVE_CONFIG_H')
glibmm2.Append(CXXFLAGS='-DG_DISABLE_DEPRECATED')
glibmm2.Append(CXXFLAGS='-DG_LOG_DOMAIN=\\\"glibmm\\\"')

glibmm2_configure_script = glibmm2.Command ('configure', 'configure.ac', 'cd libs/glibmm2; ./autogen.sh; cd -', ENV=os.environ)
glibmm2_config_h = glibmm2.Command('glibmmconfig.h', [glibmm2_configure_script, 'glibmmconfig.h.in'], 'cd libs/glibmm2; ./configure; cd -', ENV=os.environ)

libglibmm2 = glibmm2.StaticLibrary('glibmm2', glibmm2_files)
Default([glibmm2_config_h, libglibmm2])
