#!/usr/bin/env python
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = [ 'panner_2in2out.cc' ]
    obj.defines      = [ 'PACKAGE="libardour_pan2in2out"' ]
    obj.defines     += [ 'ARDOURPANNER_DLL_EXPORTS' ]
    obj.includes     = ['.']
    obj.name         = 'libardour_pan2in2out'
    obj.target       = 'pan2in2out'
    obj.use          = 'libardour libardour_cp libpbd'
    obj.uselib       = 'GLIBMM XML OSX'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'panners')
