#!/usr/bin/env python

# Version of this package (even if built as a child)
MAJOR = '1'
MINOR = '6'
MICRO = '0'
ZRESAMPLER_VERSION = "%s.%s.%s" % (MAJOR, MINOR, MICRO)

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
ZRESAMPLER_LIB_VERSION = '1.6.0'

I18N_PACKAGE = 'libzita-resampler'

zresampler_sources = [
        'resampler.cc',
        'resampler-table.cc',
        'cresampler.cc',
        'vresampler.cc',
        'vmresampler.cc'
]

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld.stlib(features = 'cxx cxxstlib', source = zresampler_sources)
    obj.cxxflags        = [ bld.env['compiler_flags_dict']['pic'], '-O3', '-ffast-math' ]
    obj.export_includes = ['.']
    obj.includes        = ['.']
    obj.name            = 'zita-resampler'
    obj.target          = 'zita-resampler'
    obj.vnum            = ZRESAMPLER_LIB_VERSION
    obj.defines         = [ 'PACKAGE="' + I18N_PACKAGE + '"' ]
