#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import TaskGen
import os
import sys

# Variables for 'waf dist'
APPNAME = 'libsgardour'
VERSION = '1.0.0'
I18N_PACKAGE = 'libsgardour'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    conf.load('compiler_cxx')
    autowaf.configure(conf)

def bundlify(bld):
    # ensure the bundle directory folder is in place
    p = bld.path.find_dir ('.')
    # copy the object into it
    # copy the Info.plist file

def build(bld):
    if bld.is_defined ('HAVE_SOUNDGRID'):
	object = bld.program (
            source       = [ 'driver.cc' ],
            target       = 'SurfaceDriver_App',
            includes     = ['.'],
            linkflags    = '-bundle',
            use          = [ 'libardour' ],
            install_path = os.path.join(bld.env['LIBDIR'], 'ardour3'),
            defines      = ['PACKAGE="' + I18N_PACKAGE + '"',
                            'PROGRAM_NAME="' + bld.env['PROGRAM_NAME'] + '"' 
                           ]
            )
        bld (rule='mkdir -p ${TGT}', 
             target=bld.path.get_bld().make_node ('SurfaceDriver_App.bundle/Contents/MacOS'))
        bld (rule='cp ${SRC} ${TGT}', 
             target=bld.path.get_bld().make_node ('SurfaceDriver_App.bundle/Contents/Info.plist'), 
             source=bld.path.make_node ('Info.plist.in'))
        bld (rule='cp ${SRC} ${TGT}', 
             target=bld.path.get_bld().make_node('SurfaceDriver_App.bundle/Contents/MacOS/SurfaceDriver_App'), 
             source=bld.path.get_bld().make_node ('SurfaceDriver_App'))

def shutdown():
    autowaf.shutdown()
