#!/bin/sh

download=
clean=
parallel=2

while [ $# -gt 0 ] ; do
   case $1 in
    --down*) download=1 ; shift ;;
    --clean*) clean=1 ; shift ;;
    -j*) parallel=`echo $1 | sed 's/-j//'` ; shift ;;
   esac
done


if [ $download ] ; then
    set -e
    echo xz
    if [ ! -f xz-5.0.3.tar.bz2 ] ; then
	curl -LO http://tukaani.org/xz/xz-5.0.3.tar.bz2
    fi
    echo m4
    if [ ! -f m4-1.4.16.tar.bz2 ] ; then
	curl -O http://ftp.gnu.org/gnu/m4/m4-1.4.16.tar.bz2
    fi
    echo automake
    if [ ! -f automake-1.11.3.tar.gz ] ; then
	curl -O http://ftp.gnu.org/gnu/automake/automake-1.11.3.tar.gz
    fi
    echo autoconf
    if [ ! -f autoconf-2.68.tar.bz2 ] ; then
	curl -O http://ftp.gnu.org/gnu/autoconf/autoconf-2.68.tar.bz2
    fi
    echo libtool
    if [ ! -f libtool-2.4.2.tar.gz ] ; then
	curl -O http://mirrors.ibiblio.org/pub/mirrors/gnu/ftp/gnu/libtool/libtool-2.4.2.tar.gz
    fi
    echo make
    if [ ! -f make-3.82.tar.bz2 ] ; then
	curl -O http://ftp.gnu.org/gnu/make/make-3.82.tar.bz2
    fi
    echo bison
    if [ ! -f bison-2.5.tar.bz2 ] ; then
	curl -O ftp://ftp.gnu.org/gnu/bison/bison-2.5.tar.bz2
    fi
    echo glib
    if [ ! -f glib-2.31.18.tar.xz ] ; then
	curl -LO http://ftp.gnome.org/pub/gnome/sources/glib/2.31/glib-2.31.18.tar.xz
    fi
    echo pkg-config
    if [ ! -f pkg-config-0.26.tar.gz ] ; then
	curl -O http://pkgconfig.freedesktop.org/releases/pkg-config-0.26.tar.gz
    fi
    echo readline
    if [ ! -f readline-6.2.tar.gz ] ; then
	curl -O ftp://ftp.cwru.edu/pub/bash/readline-6.2.tar.gz
    fi
    echo zlib
    if [ ! -f zlib-1.2.6.tar.bz2 ] ; then
	curl -O http://zlib.net/zlib-1.2.6.tar.bz2
    fi
    echo libiconv
    if [ ! -f libiconv-1.14.tar.gz ] ; then
	curl -O ftp://ftp.gnu.org/gnu/libiconv/libiconv-1.14.tar.gz
    fi
    echo gettext
    if [ ! -f gettext-0.18.1.1.tar.gz ] ; then
	curl -O http://ftp.gnu.org/pub/gnu/gettext/gettext-0.18.1.1.tar.gz
    fi
    echo libxml2
    if [ ! -f libxml2-2.7.8.tar.gz ] ; then
	curl -O ftp://xmlsoft.org/libxslt/libxml2-2.7.8.tar.gz
    fi
    echo libxslt
    if [ ! -f libxslt-1.1.26.tar.gz ] ; then
	curl -O ftp://xmlsoft.org/libxslt/libxslt-1.1.26.tar.gz
    fi
    echo tiff
    if [ ! -f tiff-4.0.1.tar.gz ] ; then
	curl -O ftp://ftp.remotesensing.org/pub/libtiff/tiff-4.0.1.tar.gz
    fi
    echo png
    if [ ! -f libpng-1.5.9.tar.gz ] ; then
	curl -O ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng-1.5.9.tar.gz
    fi
    echo jpeg
    if [ ! -f jpegsrc.v8d.tar.gz ] ; then
	curl -O http://www.ijg.org/files/jpegsrc.v8d.tar.gz
    fi
    echo perl xml parser
    if [ ! -f XML-Parser-2.41.tar.gz ] ; then
	curl -L -o XML-Parser-2.41.tar.gz http://search.cpan.org/CPAN/authors/id/T/TO/TODDR/XML-Parser-2.41.tar.gz
    fi
    echo perl xml
    if [ ! -f XML-Simple-2.18.tar.gz ] ; then
	curl -L -o XML-Simple-2.18.tar.gz http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/XML-Simple-2.18.tar.gz
    fi
    echo atk
    if [ ! -f atk-2.2.0.tar.bz2 ] ; then
	curl -O http://ftp.gnome.org/pub/GNOME/sources/atk/2.2/atk-2.2.0.tar.bz2
    fi
    echo gnome-common
    if [ ! -f gnome-common-2.34.0.tar.bz2 ] ; then
	curl -O http://ftp.acc.umu.se/pub/gnome/sources/gnome-common/2.34/gnome-common-2.34.0.tar.bz2
    fi
    echo gtk-doc
    if [ ! -f gtk-doc-1.18.tar.bz2 ] ; then
	curl -O http://ftp.gnome.org/pub/GNOME/sources/gtk-doc/1.18/gtk-doc-1.18.tar.bz2
    fi
    echo gnome-doc
    if [ ! -f gnome-doc-utils-0.20.6.tar.bz2 ] ; then
	curl -O http://ftp.acc.umu.se/pub/gnome/sources/gnome-doc-utils/0.20/gnome-doc-utils-0.20.6.tar.bz2
    fi
    echo pixman
    if [ ! -f pixman-0.24.4.tar.gz ] ; then
	curl -O http://cgit.freedesktop.org/pixman/snapshot/pixman-0.24.4.tar.gz
    fi
    echo ffi
    if [ ! -f libffi-3.0.10.tar.gz ] ; then
	curl -O ftp://sourceware.org/pub/libffi/libffi-3.0.10.tar.gz
    fi
    echo freetype
    if [ ! -f freetype-2.4.8.tar.bz2 ] ; then
	curl -L -o freetype-2.4.8.tar.bz2 http://sourceforge.net/projects/freetype/files/freetype2/2.4.8/freetype-2.4.8.tar.bz2/download
    fi
    echo fontconfig
    if [ ! -f fontconfig-2.8.0.tar.gz ] ; then
	curl -LO http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.8.0.tar.gz
    fi
    echo cairo
    if [ ! -f cairo-1.10.2.tar.gz ] ; then
	curl -LO http://cairographics.org/releases/cairo-1.10.2.tar.gz
    fi
    echo pango
    if [ ! -f pango-1.29.5.tar.bz2 ] ; then
	curl -LO http://ftp.gnome.org/pub/GNOME/sources/pango/1.29/pango-1.29.5.tar.bz2
    fi
    echo gdk-pixbuf
    if [ ! -f gdk-pixbuf-2.25.2.tar.xz ] ; then
	curl -LO http://ftp.gnome.org/pub/GNOME/sources/gdk-pixbuf/2.25/gdk-pixbuf-2.25.2.tar.xz
    fi
    echo intltool
    if [ ! -f intltool-0.50.2.tar.gz ] ; then
	curl -LO https://launchpad.net/intltool/trunk/0.50.2/+download/intltool-0.50.2.tar.gz
    fi
    echo gtk-osx-docbook
    if [ ! -f gtk-osx-docbook-1.0.tar.gz ] ; then
	curl -L -o gtk-osx-docbook-1.0.tar.gz http://sourceforge.net/projects/gtk-osx/files/GTK-OSX%20Build/gtk-osx-docbook-1.0.tar.gz/download
    fi
    echo gobject-introspection
    if [ ! -f gobject-introspection-1.31.10.tar.xz ] ; then
	curl -LO http://ftp.gnome.org/pub/GNOME/sources/gobject-introspection/1.31/gobject-introspection-1.31.10.tar.xz
    fi

    echo "GTK+ (2.24 branch)"
    git clone git://git.gnome.org/gtk+
    git checkout --track -b gtk-2-24 origin/gtk-2-24

    exit 0
fi

# target for install
PREFIX=$HOME/gtk/inst

if [ $clean ] ; then
    rm -rf `ls -ld * | awk '/^d/ {print $9;}' | grep -v gtk+`
    # have to use sudo because we used sudo for libxml2 install, sigh.
    sudo rm -rf $PREFIX
    exit 0
fi

mkdir -p $PREFIX

export MAKEFLAGS=-j$parallel
PATH=$PREFIX/bin:$PATH

if uname -a | grep --silent arwin ; then
    
    # its OS X! run for the hills !!

    export DYLD_FALLBACK_LIBRARY_PATH=$PREFIX/lib${DYLD_FALLBACK_LIBRARY_PATH:+:$DYLD_FALLBACK_LIBRARY_PATH}
    # force compilation to use 10.4 APIs only. could be overkill, but better safe than sorry
    GLOBAL_CFLAGS="-DMAC_OS_X_VERSION_MIN_REQUIRED=1040 -DMAC_OSX_VERSION_MAX_ALLOWED=1040 -mmacosx-version-min=10.4"
    # for 10.5 and above, add to CFLAGS
    # -sysroot=/Developer/SDKs/MacOSX10.4u.sdk"
    GLOBAL_LDFLAGS=
    # for 10.5 and above, add to LDFLAGS
    # "-syslibroot /Developer/SDKs/MacOSX10.4u.sdk"
    export MACOSX_DEPLOYMENT_TARGET=10.4
    # If the default python is not new enough, set PYTHON to point to a 
    # suitably new (2.7 or later) version of Python's framework
    PYTHON=
    #PYTHON=/Library/Frameworks/Python.framework/Versions/2.7
else 
    export LD_LIBRARY_PATH=$PREFIX/lib{$LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    GLOBAL_CFLAGS=
    GLOBAL_LDFLAGS=
fi

export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig

#tar xf gdk-pixbuf-2.25.2.tar.xz && (cd gdk-pixbuf-2.25.2 && LDFLAGS="$GLOBAL_LDFLAGS -L$PREFIX/lib" CFLAGS="-I$PREFIX/include $GLOBAL_CFLAGS" ./configure --prefix=$PREFIX && make && make install)
#sudo ln -s $PREFIX/include/libintl.h /usr/include
#tar xf gobject-introspection-1.31.10.tar.xz && (cd gobject-introspection-1.31.10 && LDFLAGS="$GLOBAL_LDFLAGS -L$PREFIX/lib -lintl" CFLAGS="-I$PREFIX/include $GLOBAL_CFLAGS" ./configure --prefix=$PREFIX --disable-silent-rules && make && make install)
#sudo rm /usr/include/libintl.h
#
# now gtk itself
# 
#
(cd gtk+ && CFLAGS="$GLOBAL_CFLAGS" LDFLAGS="$GLOBAL_LDFLAGS" sh autogen.sh --enable-maintainer-mode --prefix=$PREFIX --libdir=$PREFIX/lib --disable-cups --disable-papi --disable-introspection --with-gdktarget=quartz && make && make install)
