#!/bin/sh

tooldir=`dirname $0`

$tooldir/luals | awk '
BEGIN {
	type_name_map["dsp"] = "DSP";
	type_name_map["EditorAction"] = "Editor Actions";
	type_name_map["EditorHook"] = "Editor Hooks";
	type_name_map["SessionInit"] = "Session Initialization";
	type_name_map["session"] = "Session";
}
/T:/ {
	split ($0, a, ":");

	if (a[2] in type_name_map) {
		type_name = type_name_map[a[2]];
	} else {
		type_name = a[2];
	}

	types[scripts] = type_name;
	type_names[type_name] = type_name;
	names[scripts] = a[4];
	descriptions[scripts] = a[6];
	scripts++;
}
END {
	tnc = asort (type_names);

	for (tn = 1; tn <= tnc; ++tn) {
		printf ("<h2>%s</h2>\n<dl>\n", type_names[tn]);
		for (s = 1; s <= scripts; ++s) {
			if (types[s] == type_names[tn]) {
				printf ("<dt>%s</dt><dd>%s<dd>\n", names[s], descriptions[s]);
			}
		}
		printf ("</dl>\n");
	}
}
'
