#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import Options
import os

# Mandatory variables
top = '.'
out = 'build'


def options(opt):

    autowaf.set_options(opt)

def sub_config_and_use(conf, name, has_objects = True):
    conf.recurse(name)
    autowaf.set_local_lib(conf, name, has_objects)

def configure(conf):
    autowaf.set_recursive()

    panners = [ '2in2out', '1in2out', 'vbap', 'stereobalance' ]

    for i in panners:
        sub_config_and_use(conf, i)

def build(bld):
    panners = [ '2in2out', '1in2out', 'vbap', 'stereobalance' ]

    for i in panners:
        bld.recurse(i)
