#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            console1_interface.cc
            console1.cc
            c1_operations.cc
            c1_plugin_operations.cc
            c1_gui.cc
    '''
    obj.defines      = [ 'PACKAGE="ardour_console1"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = [ '.', './console1']
    obj.name         = 'libardour_console1'
    obj.target       = 'ardour_console1'
    obj.uselib       = 'SIGCPP XML OSX'
    obj.use          = 'libardour libardour_cp libardour_midisurface libgtkmm2ext libpbd libevoral libtemporal'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')
    if bld.is_defined('YTK'):
        obj.use    += ' libytkmm'
        obj.uselib += ' GLIBMM GIOMM PANGOMM'
    else:
        obj.uselib += ' GTKMM'
