# -*- python -*-

import os
import os.path
import glob

pangomm_files = glob.glob('pangomm/*.cc')

Import('env libraries install_prefix')
pangomm = env.Copy()
pangomm.Merge([libraries['glibmm2'], libraries['cairo'], libraries['cairomm'], libraries['pango'], libraries['pangocairo'], libraries['sigc2']])

libpangomm = pangomm.SharedLibrary('pangomm', pangomm_files)
Default(libpangomm)

env.Alias('install', env.Install(os.path.join(install_prefix, env['LIBDIR'], 'ardour2'), libpangomm))

env.Alias('tarball', env.Distribute (env['DISTTREE'],
                                     [ 'SConscript', 'pangomm.h'] + 
				     pangomm_files + 
				     glob.glob('pangomm/*.h') +
				     glob.glob('pangomm/private/*.h')
				     ))
