# -*- python -*-

import glob
import os

pangomm_files = glob.glob('pangomm/*.cc')

Import('env libraries')
pangomm = env.Copy()
pangomm.Merge([libraries['glibmm2'], libraries['pango'], libraries['sigc2']])

libpangomm = pangomm.SharedLibrary('pangomm', pangomm_files)
Default(libpangomm)

env.Alias('tarball', env.Distribute (env['DISTTREE'],
                                     [ 'SConscript', 'pangomm.h'] + 
				     pangomm_files + 
				     glob.glob('pangomm/*.h') +
				     glob.glob('pangomm/private/*.h')
				     ))
