#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import Options
import os

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    conf.load('compiler_cxx')
    autowaf.configure(conf)

def build(bld):
    bld (export_includes = ['.'],
         includes        = ['.'],
         name            = 'libtimecode_includes'
         )

    bld.stlib (cxxflags = [ '-fPIC' ],
               source   = [ 'src/time.cc', 'src/bbt_time.cc' ],
               target   = 'libtimecode',
               use      = 'libtimecode_includes'
               )

def shutdown():
    autowaf.shutdown()
