#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import Options
import os

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    conf.load('compiler_cxx')
    autowaf.configure(conf)

def build(bld):
    bld.shlib (
               source   = [ 'time.cc', 'bbt_time.cc' ],
               name     = 'libtemporal',
               target   = 'temporal',
               includes = ['.'],
               export_includes = ['.'],
               defines  = [ 'LIBTEMPORAL_DLL_EXPORTS' ],
               install_path = bld.env['LIBDIR']
               )

def shutdown():
    autowaf.shutdown()
